"""Versioned wire contracts exchanged with the NarrativeX control plane."""

from .fingerprint import request_fingerprint
from .models import (
    ArtifactAccess,
    ArtifactRef,
    AudioAlignInputs,
    AudioFormat,
    AudioSynthesizeInputs,
    ComputeError,
    ComputeObservation,
    ComputeTask,
    ErrorCategory,
    ExecutionMetrics,
    ExecutionState,
    ExecutorCapability,
    ImageGenerateInputs,
    MediaValidateInputs,
    ModelRef,
    ProtocolModel,
    TaskConstraints,
    TaskDescriptor,
    VoiceSelection,
    WorkerCapabilities,
    WorkerLimits,
)

__all__ = [
    "ArtifactAccess",
    "ArtifactRef",
    "AudioAlignInputs",
    "AudioFormat",
    "AudioSynthesizeInputs",
    "ComputeError",
    "ComputeObservation",
    "ComputeTask",
    "ErrorCategory",
    "ExecutionMetrics",
    "ExecutionState",
    "ExecutorCapability",
    "ImageGenerateInputs",
    "MediaValidateInputs",
    "ModelRef",
    "ProtocolModel",
    "TaskConstraints",
    "TaskDescriptor",
    "VoiceSelection",
    "WorkerCapabilities",
    "WorkerLimits",
    "request_fingerprint",
]
