package com.narrativex.backend.feature.storyboard.application.port.in;

/** Typed specification for HookPlan generated by Gemini Story Director. */
public record HookPlanSpec(
    String promise,
    String conflict,
    String curiosityQuestion,
    String visualHook,
    String dialogueHook,
    String withheldInformation,
    String payoffBeatTitle) {}
