package com.narrativex.backend.feature.storyboard.application.port.in;

import com.narrativex.backend.feature.storyboard.domain.enums.AttentionEventType;
import java.util.List;

/** Typed specification for RetentionMap generated by Gemini Story Director. */
public record RetentionMapSpec(
    List<Double> tensionCurve,
    List<String> openQuestions,
    List<String> resolvedQuestions,
    List<AttentionEventSpec> attentionEvents) {

  public record AttentionEventSpec(
      AttentionEventType eventType, long timeOffsetMs, String description, String severity) {}
}
