import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        slate: {
          100: "rgb(var(--palette-slate-100) / <alpha-value>)",
          200: "rgb(var(--palette-slate-200) / <alpha-value>)",
          300: "rgb(var(--palette-slate-300) / <alpha-value>)",
          400: "rgb(var(--palette-slate-400) / <alpha-value>)",
          500: "rgb(var(--palette-slate-500) / <alpha-value>)",
          600: "rgb(var(--palette-slate-600) / <alpha-value>)",
          700: "rgb(var(--palette-slate-700) / <alpha-value>)",
          800: "rgb(var(--palette-slate-800) / <alpha-value>)",
          900: "rgb(var(--palette-slate-900) / <alpha-value>)",
          950: "rgb(var(--palette-slate-950) / <alpha-value>)",
        },
        purple: {
          200: "rgb(var(--palette-orange-200) / <alpha-value>)",
          300: "rgb(var(--palette-orange-300) / <alpha-value>)",
          400: "rgb(var(--palette-orange-400) / <alpha-value>)",
          500: "rgb(var(--palette-orange-500) / <alpha-value>)",
          600: "rgb(var(--palette-orange-600) / <alpha-value>)",
          700: "rgb(var(--palette-orange-700) / <alpha-value>)",
          800: "rgb(var(--palette-orange-800) / <alpha-value>)",
          900: "rgb(var(--palette-orange-900) / <alpha-value>)",
          950: "rgb(var(--palette-orange-950) / <alpha-value>)",
        },
        indigo: {
          400: "rgb(var(--palette-orange-400) / <alpha-value>)",
          500: "rgb(var(--palette-orange-500) / <alpha-value>)",
          600: "rgb(var(--palette-orange-600) / <alpha-value>)",
          700: "rgb(var(--palette-orange-700) / <alpha-value>)",
          800: "rgb(var(--palette-orange-800) / <alpha-value>)",
          900: "rgb(var(--palette-orange-900) / <alpha-value>)",
        },
        background: "var(--background)",
        foreground: "var(--foreground)",
        surface: {
          DEFAULT: "var(--surface)",
          2: "var(--surface-2)",
          3: "var(--surface-3)",
          dark: "var(--surface-dark)",
          card: "var(--surface-card)",
          panel: "var(--surface-panel)",
          elevated: "var(--surface-elevated)",
          input: "var(--surface-input)",
          storyboard: "var(--surface-storyboard)",
          "storyboard-card": "var(--surface-storyboard-card)",
        },
        border: {
          DEFAULT: "var(--border)",
          subtle: "var(--border-subtle)",
          dark: "var(--border-dark)",
          darker: "var(--border-darker)",
          storyboard: "var(--border-storyboard)",
          "storyboard-strong": "var(--border-storyboard-strong)",
          glow: "var(--border-glow)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          hover: "var(--primary-hover)",
          light: "var(--primary-light)",
          muted: "var(--primary-muted)",
        },
        success: {
          DEFAULT: "var(--success)",
          bg: "var(--success-bg)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          bg: "var(--warning-bg)",
        },
        danger: {
          DEFAULT: "var(--danger)",
          bg: "var(--danger-bg)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
          dim: "var(--text-dim)",
        },
        badge: {
          purple: "var(--badge-purple)",
          "purple-bg": "var(--badge-purple-bg)",
          "purple-border": "var(--badge-purple-border)",
          blue: "var(--badge-blue)",
          "blue-bg": "var(--badge-blue-bg)",
          "blue-border": "var(--badge-blue-border)",
          orange: "var(--badge-orange)",
          "orange-bg": "var(--badge-orange-bg)",
          "orange-border": "var(--badge-orange-border)",
          green: "var(--badge-green)",
          "green-bg": "var(--badge-green-bg)",
          "green-border": "var(--badge-green-border)",
          amber: "var(--badge-amber)",
          "amber-bg": "var(--badge-amber-bg)",
          "amber-border": "var(--badge-amber-border)",
          slate: "var(--badge-slate)",
          "slate-bg": "var(--badge-slate-bg)",
          "slate-border": "var(--badge-slate-border)",
        },
      },
    },
  },
  plugins: [],
};

export default config;
