"""Shared prompt instructions used by active Chapter analysis prompts."""

SCENE_SEGMENTATION_INSTRUCTIONS = (
    "Segment the chapter into semantically meaningful narrative scenes for story-to-video, not "
    "traditional screenplay scenes. A scene is one coherent narrative phase with one dominant "
    "dramatic purpose. Do not assume that the same location, continuous time, or the same cast "
    "means the content belongs to one scene. The same room may legitimately contain several "
    "scenes when the narrative purpose changes. Start a new scene when there is a meaningful "
    "change in character goal, active conflict, major revelation, narrative mode, exposition "
    "phase, action phase, POV/focus, or major emotional/dramatic turn; location and time changes "
    "are also valid boundaries but are not privileged over semantic changes. Strong boundaries "
    "include: discovering important new information, entering or leaving a sustained system "
    "interaction, switching between present action and substantial exposition/backstory, beginning "
    "a materially different action sequence, or shifting to another character's meaningful POV. "
    "Do not create a new scene merely for a new sentence, paragraph, speaker, facial expression, "
    "camera angle, minor gesture, or image opportunity; those belong to visual beats. "
    "Actively check for under-segmentation: if one proposed scene contains several distinct major "
    "goals, revelations, narrative modes, action phases, or mini-arcs, split it at the strongest "
    "semantic transition. Use the scene-title test: each scene should be describable by one short "
    "title expressing one dominant dramatic purpose; if the title would need 'and then' repeatedly "
    "to cover unrelated events, the scene is too broad. Also check for over-segmentation and merge "
    "adjacent fragments that still serve the same dramatic purpose. For long chapters, be "
    "suspicious of outputs with only one or two scenes when the source contains multiple strong "
    "goal/revelation/mode/action/POV transitions. Scene count must emerge from the content; never "
    "target a predetermined number of scenes. Preserve the source order and ensure every relevant "
    "story event is represented exactly once across the ordered scenes."
)

CHARACTER_PROFILE_INSTRUCTIONS = (
    " For every reusable character, extract a durable source-grounded profile in addition to "
    "identity. role should be a concise narrative role, normally LEAD, SUPPORTING, or BACKGROUND. "
    "importance is a non-negative relative relevance score, preferably 0-100. groups contains only "
    "explicit or strongly supported factions, teams, families, or relationship groups. bible is a "
    "compact narrative continuity reference containing personality, motivations, abilities, "
    "relationships, backstory, and behavior facts; do not use bible as the image identity prompt. "
    "visual_prompt is the permanent visual identity contract. It should describe stable facial "
    "geometry, eye characteristics, skin tone, permanent hair color/base silhouette, body "
    "build/proportions, permanent distinguishing marks, and permanent signature accessories when "
    "supported or canonically established. Never put current pose, expression, camera, scene "
    "lighting, current location, story action, or temporary wardrobe inside visual_prompt. "
    "age_state, hairstyle, injury, wardrobe_context, and appearance_prompt represent current "
    "timeline state. appearance_prompt represents current timeline state as one concise "
    "image-ready description; it must not redefine the permanent visual identity. Source-stated "
    "physical traits are immutable. When non-story-critical visual traits are absent, establish "
    "conservative visual defaults once when needed to make a reusable character design, provided "
    "they do not contradict the source. Once established in visual_prompt those choices are "
    "treated as canonical and must not be re-invented in later beats. Use an empty string or "
    "empty list only when a usable value truly cannot be grounded or conservatively established. "
)

LOCATION_PROFILE_INSTRUCTIONS = (
    " For every reusable location, description is the narrative description while visual_prompt "
    "is the reusable visual canon. visual_prompt should capture stable architecture, layout, "
    "materials, dominant colors, important furniture or props, doors/windows, spatial landmarks, "
    "and persistent ambient characteristics when supported. Never put current character action, "
    "current pose, shot composition, camera angle, or temporary event-specific lighting inside "
    "location visual_prompt. Prefer concrete spatial details that make later scenes recognizable "
    "as the same place. If visual details are sparse, establish conservative non-story-critical "
    "defaults once without contradicting the source, then keep them stable. "
)

IMAGE_SAFETY_ADAPTATION = (
    " IMAGE-SAFETY ADAPTATION: write every image visual_intent in provider-safe, non-graphic "
    "language. Preserve the narrative fact and emotional stakes, but translate sensitive events "
    "into indirect visual language suitable for a still illustration. Keep subjects appropriately "
    "clothed and use neutral, non-sexualized framing. Prefer facial tension, posture, distance, "
    "occlusion, off-screen implication, aftermath, and environmental cues instead of explicit "
    "physical or coercive mechanics. Avoid detailed descriptions of severe injury, exposed body "
    "detail, humiliating restraint, or other graphic treatment. Do not erase a source-backed "
    "conflict or consequence; represent it through a safer visible state that preserves what the "
    "viewer needs to understand. If age is unknown or a character may be young, use especially "
    "conservative, fully non-sexualized depiction. "
)
