import { MediaAsset } from "@/types/assets";

export const MOCK_ASSETS: MediaAsset[] = [
  {
    id: "ast-1",
    filename: "scene_06_beat_12_v01.png",
    type: "IMAGE",
    status: "APPROVED",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    fileSize: "2.4 MB",
    dimensions: "1920 × 1080",
    aspectRatio: "16:9",
    quality: "Standard",
    createdAt: "17/08/2026 14:45",
    provider: "SD 2026.01",
    projectTitle: "Huyền Thoại Kiếm Thần",
    chapterTitle: "06 — Cuộc hành quân đến phương Bắc",
    sceneTitle: "02 — Giữa cơn bão tuyết",
    beatTitle: "03",
    attempt: "02 / 02",
    prompt: "A massive medieval dark stone castle standing amidst deep snow in the northern frozen kingdom, dramatic cinematic lighting, photorealistic 8k.",
    usedIn: [
      {
        type: "scene_beat",
        title: "Scene 02 — Giữa cơn bão tuyết",
        subtitle: "Beat 03 — Visual 01",
        linkText: "Xem trong Storyboard",
        targetView: "storyboard",
      },
    ],
  },
  {
    id: "ast-2",
    filename: "char_eleanor_ref_front.png",
    type: "REFERENCE",
    status: "LOCKED",
    thumbnailUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
    fileSize: "1.1 MB",
    dimensions: "1024 × 1536",
    aspectRatio: "2:3",
    quality: "Master",
    createdAt: "16/08/2026 10:20",
    provider: "Character Studio v2.4",
    projectTitle: "Huyền Thoại Kiếm Thần",
    characterName: "Eleanor",
    attempt: "01 / 01",
    prompt: "Master character reference portrait of Princess Eleanor, blonde braided hair, emerald green eyes, golden royal circlet, pristine lighting.",
    usedIn: [
      {
        type: "character",
        title: "Nhân vật: Eleanor (Princess of Light)",
        subtitle: "Locked Character Version 03",
        linkText: "Xem trong Character Bible",
        targetView: "character-bible",
      },
    ],
  },
  {
    id: "ast-3",
    filename: "scene_06_beat_15_v02.png",
    type: "IMAGE",
    status: "NEEDS_REVIEW",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop",
    fileSize: "2.6 MB",
    dimensions: "1920 × 1080",
    aspectRatio: "16:9",
    quality: "Standard",
    createdAt: "17/08/2026 14:50",
    provider: "SD 2026.01",
    projectTitle: "Huyền Thoại Kiếm Thần",
    chapterTitle: "06 — Cuộc hành quân đến phương Bắc",
    sceneTitle: "03 — Sinh vật băng giá",
    beatTitle: "01",
    attempt: "02 / 03",
    prompt: "Warrior advancing through heavy raging blizzard with glowing blue sword drawn, silhouette of monstrous ice creature looming in distance.",
    usedIn: [
      {
        type: "scene_beat",
        title: "Scene 03 — Sinh vật băng giá",
        subtitle: "Beat 01 — Visual 02",
        linkText: "Xem trong Visual Review",
        targetView: "visual-review",
      },
    ],
  },
  {
    id: "ast-4",
    filename: "scene_05_final_v03.mp4",
    type: "VIDEO",
    status: "GENERATED",
    thumbnailUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop",
    fileSize: "2.1 MB",
    dimensions: "1920 × 1080",
    duration: "00:08",
    aspectRatio: "16:9",
    quality: "High",
    createdAt: "17/08/2026 11:30",
    provider: "AnimateDiff Studio v3",
    projectTitle: "Huyền Thoại Kiếm Thần",
    chapterTitle: "05 — Đại chiến Hắc Vân",
    sceneTitle: "04 — Trận chiến cổng thành",
    beatTitle: "Final",
    attempt: "03 / 03",
    usedIn: [
      {
        type: "chapter",
        title: "Chapter 05 — Đại chiến Hắc Vân",
        subtitle: "Rendered Scene Clip 04",
        linkText: "Xem trong Storyboard",
        targetView: "storyboard",
      },
    ],
  },
  {
    id: "ast-5",
    filename: "narration_chapter_06_v02.wav",
    type: "AUDIO",
    status: "READY",
    thumbnailUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=800&auto=format&fit=crop",
    fileSize: "48.2 MB",
    duration: "07:36",
    audioSampleRate: "44.1 kHz • WAV",
    createdAt: "16/08/2026 18:15",
    provider: "ElevenLabs Studio Pro",
    projectTitle: "Huyền Thoại Kiếm Thần",
    chapterTitle: "06 — Cuộc hành quân đến phương Bắc",
    beatTitle: "Full Chapter Narration",
    audioWaveform: [25, 45, 60, 80, 50, 65, 90, 75, 40, 60, 85, 95, 70, 45, 60, 80, 55, 70, 90, 65, 40, 55, 75, 90, 60, 45, 30, 60, 85, 70],
    usedIn: [
      {
        type: "chapter",
        title: "Chapter 06 — Cuộc hành quân đến phương Bắc",
        subtitle: "Main TTS Master Audio Track",
        linkText: "Xem Chapter Workspace",
        targetView: "workspace",
      },
    ],
  },
  {
    id: "ast-6",
    filename: "location_hac_van_ref_01.jpg",
    type: "REFERENCE",
    status: "APPROVED",
    thumbnailUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800&auto=format&fit=crop",
    fileSize: "1.8 MB",
    dimensions: "1920 × 1080",
    aspectRatio: "16:9",
    quality: "High",
    createdAt: "15/08/2026 09:30",
    provider: "WorldBuilder Studio",
    projectTitle: "Huyền Thoại Kiếm Thần",
    locationName: "Thành Hắc Vân",
    attempt: "01 / 01",
    usedIn: [
      {
        type: "location",
        title: "Bối cảnh: Thành Hắc Vân (Dark Cloud Citadel)",
        subtitle: "Location Style Bible Reference",
        linkText: "Xem Storyboard",
        targetView: "storyboard",
      },
    ],
  },
  {
    id: "ast-7",
    filename: "motion_sword_idle_01.mp4",
    type: "MOTION",
    status: "GENERATED",
    thumbnailUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop",
    fileSize: "1.4 MB",
    dimensions: "1024 × 1024",
    duration: "00:04",
    aspectRatio: "1:1",
    quality: "24fps",
    createdAt: "17/08/2026 13:10",
    provider: "MotionEngine v1.8",
    projectTitle: "Huyền Thoại Kiếm Thần",
    characterName: "Kael (Hiệp sĩ rồng)",
    usedIn: [
      {
        type: "character",
        title: "Kael — Sword Combat Idle Loop",
        subtitle: "Motion Preset Layer",
        linkText: "Xem trong Character Bible",
        targetView: "character-bible",
      },
    ],
  },
  {
    id: "ast-8",
    filename: "sfx_wind_storm_v01.wav",
    type: "AUDIO",
    status: "PROCESSING",
    thumbnailUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop",
    fileSize: "3.2 MB",
    duration: "00:30",
    audioSampleRate: "44.1 kHz • WAV",
    createdAt: "17/08/2026 15:10",
    progressPercent: 65,
    projectTitle: "Huyền Thoại Kiếm Thần",
    chapterTitle: "06 — Cuộc hành quân đến phương Bắc",
    audioWaveform: [10, 20, 35, 50, 65, 80, 95, 85, 70, 60, 50, 40, 30, 20, 15, 30, 45, 60, 75, 90, 80, 65, 50, 35, 20, 15, 10, 25, 40, 30],
    usedIn: [
      {
        type: "chapter",
        title: "Chapter 06 — Scene 02 Blizzard SFX",
        subtitle: "Ambient Audio Layer (Rendering)",
        linkText: "Xem Chapter Workspace",
        targetView: "workspace",
      },
    ],
  },
  {
    id: "ast-9",
    filename: "scene_04_beat_08_v01.png",
    type: "IMAGE",
    status: "APPROVED",
    thumbnailUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    fileSize: "2.8 MB",
    dimensions: "1920 × 1080",
    aspectRatio: "16:9",
    quality: "Standard",
    createdAt: "17/08/2026 09:20",
    provider: "SD 2026.01",
    projectTitle: "Huyền Thoại Kiếm Thần",
    chapterTitle: "04 — Thành Hắc Vân",
    sceneTitle: "02 — Do thám địch quân",
    beatTitle: "08",
    usedIn: [
      {
        type: "scene_beat",
        title: "Scene 02 — Do thám địch quân",
        subtitle: "Beat 08 — Visual 01",
        linkText: "Xem trong Storyboard",
        targetView: "storyboard",
      },
    ],
  },
  {
    id: "ast-10",
    filename: "scene_06_beat_22_v01.png",
    type: "IMAGE",
    status: "FAILED",
    thumbnailUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop",
    fileSize: "1.9 MB",
    dimensions: "1920 × 1080",
    aspectRatio: "16:9",
    quality: "Standard",
    createdAt: "17/08/2026 15:02",
    provider: "SD 2026.01",
    projectTitle: "Huyền Thoại Kiếm Thần",
    chapterTitle: "06 — Cuộc hành quân đến phương Bắc",
    sceneTitle: "04 — Giao tranh vách đá",
    beatTitle: "22",
    attempt: "01 / 03",
    prompt: "Extreme blizzard cliff battle scene with soldiers climbing vertical ice peaks.",
    usedIn: [
      {
        type: "scene_beat",
        title: "Scene 04 — Giao tranh vách đá",
        subtitle: "Beat 22 — Generation Timeout",
        linkText: "Thử lại trong Storyboard",
        targetView: "storyboard",
      },
    ],
  },
  {
    id: "ast-11",
    filename: "project_full_draft_v01.mp4",
    type: "FINAL_OUTPUT",
    status: "COMPLETED",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    fileSize: "1.2 GB",
    dimensions: "1920 × 1080",
    duration: "58:42",
    aspectRatio: "16:9",
    quality: "Master 1080p",
    createdAt: "17/08/2026 15:30",
    provider: "NarrativeX Cinema Pipeline",
    projectTitle: "Huyền Thoại Kiếm Thần",
    beatTitle: "10 Chapters Full Feature Cut",
    usedIn: [
      {
        type: "project",
        title: "Huyền Thoại Kiếm Thần — Full Feature Video",
        subtitle: "6 Ready Chapters Merged",
        linkText: "Xem Long-form Preview",
        targetView: "preview",
      },
    ],
  },
];
