import { Character, Project, ProjectCharacter } from "@/types/studio";

type CharacterSeed = Omit<Character, "canonicalIdentity" | "latestVersion"> & {
  role: string;
  projectName: string;
  projectId: string;
  version: number;
  isLocked: boolean;
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    title: "Huyền Thoại Ánh Sáng",
    description: "Câu chuyện về cuộc hành trình của một nhóm anh hùng chống lại thế lực bóng tối để khôi phục lại viên ngọc cổ đại.",
    updatedAt: "2 giờ trước",
    progress: 25,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 24,
    locationCount: 18,
    chapterCount: 15,
    sceneCount: 87,
    visualBeatsCount: 156,
  },
  {
    id: "proj-2",
    title: "Dòng Máu Rồng",
    description: "Sự trỗi dậy của đế chế rồng ngàn năm và bí mật về vương triều bị lãng quên.",
    updatedAt: "1 ngày trước",
    progress: 80,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 16,
    locationCount: 12,
    chapterCount: 10,
    sceneCount: 64,
    visualBeatsCount: 120,
  },
  {
    id: "proj-3",
    title: "Đường Về Nhà",
    description: "Hành trình cô đơn qua những vùng đất hoang tàn của một lữ khách tìm lại quê hương.",
    updatedAt: "3 ngày trước",
    progress: 100,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop",
    genre: "Sci-Fi",
    language: "Tiếng Việt",
    aspectRatio: "9:16",
    quality: "Standard",
    characterCount: 8,
    locationCount: 14,
    chapterCount: 8,
    sceneCount: 42,
    visualBeatsCount: 95,
  },
  {
    id: "proj-4",
    title: "Bí Ẩn Đảo Sương Mù",
    description: "Hòn đảo huyền bí xuất hiện giữa đại dương và lời nguyền của những thủy thủ mất tích.",
    updatedAt: "1 tuần trước",
    progress: 100,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    genre: "Kinh dị",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 12,
    locationCount: 9,
    chapterCount: 6,
    sceneCount: 38,
    visualBeatsCount: 78,
  },
  {
    id: "proj-5",
    title: "Chiến Binh Cuối Cùng",
    description: "Người bảo hộ cuối cùng của vương triều phương Bắc trong trận chiến định mệnh.",
    updatedAt: "1 ngày trước",
    progress: 50,
    isFavorite: false,
    coverImage: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 19,
    locationCount: 15,
    chapterCount: 12,
    sceneCount: 70,
    visualBeatsCount: 135,
  },
  {
    id: "proj-6",
    title: "Ký Ức Vĩnh Hằng",
    description: "Khi ký ức của con người có thể được lưu trữ và tái hiện trong không gian lượng tử.",
    updatedAt: "1 tuần trước",
    progress: 40,
    isFavorite: false,
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
    genre: "Sci-Fi",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 14,
    locationCount: 8,
    chapterCount: 9,
    sceneCount: 52,
    visualBeatsCount: 104,
  },
  {
    id: "proj-7",
    title: "Thành Phố Nổi",
    description: "Cuộc sống trên những pháo đài bay lơ lửng trên tầng bình lưu sau đại hồng thủy.",
    updatedAt: "1 tuần trước",
    progress: 75,
    isFavorite: false,
    coverImage: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop",
    genre: "Sci-Fi",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 22,
    locationCount: 16,
    chapterCount: 14,
    sceneCount: 80,
    visualBeatsCount: 145,
  },
  {
    id: "proj-8",
    title: "Trái Tim Băng Giá",
    description: "Lời nguyền mùa đông vĩnh cửu bao phủ lãnh nguyên tuyết trắng phương Bắc.",
    updatedAt: "2 tuần trước",
    progress: 10,
    isFavorite: false,
    coverImage: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "Standard",
    characterCount: 10,
    locationCount: 7,
    chapterCount: 5,
    sceneCount: 28,
    visualBeatsCount: 60,
  },
];

export const MOCK_CHARACTER_SEEDS: CharacterSeed[] = [
  {
    id: "char-1",
    name: "Eleanor",
    role: "Nữ chính",
    projectName: "Huyền Thoại Ánh Sáng",
    projectId: "proj-1",
    version: 2,
    isLocked: true,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop",
    description: "Nữ chính của câu chuyện, công chúa của vương quốc Eldoria, sở hữu sức mạnh ánh sáng cổ xưa truyền qua nhiều thế hệ.",
    gender: "Nữ",
    age: 19,
    height: "165cm",
    hairColor: "Vàng ánh kim",
    eyeColor: "Xanh ngọc",
    appearance: "Mái tóc vàng gợn sóng buông dài, đôi mắt ngọc lục bảo sắc sảo. Thường mặc lễ phục hoàng gia đính ngọc trai hoặc giáp bạc chiến trận nhẹ nhàng.",
    personality: "Kiên cường, quả cảm, giàu lòng trắc ẩn nhưng đôi khi quá nghiêm khắc với bản thân.",
    costume: "Trang phục chiến binh dạ quang Eldoria với đường nét thêu chỉ bạc và áo choàng lụa xanh sapphire.",
    relationships: "Đồng đội thân thiết với Kael, được Lyria bảo hộ pháp thuật, Darius là người thầy huấn luyện kiếm thuật.",
    referenceAssets: [
      {
        id: "ref-1",
        title: "Chân dung chính diện",
        imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
        type: "front",
      },
      {
        id: "ref-2",
        title: "Góc nghiêng 45 độ",
        imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop",
        type: "side",
      },
      {
        id: "ref-3",
        title: "Trang phục chiến trận",
        imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop",
        type: "costume",
      },
      {
        id: "ref-4",
        title: "Biểu cảm niệm chú",
        imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=400&auto=format&fit=crop",
        type: "expression",
      },
      {
        id: "ref-5",
        title: "Áo choàng hoàng gia",
        imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=400&auto=format&fit=crop",
        type: "portrait",
      },
      {
        id: "ref-6",
        title: "Tư thế cận chiến",
        imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=400&auto=format&fit=crop",
        type: "action",
      },
    ],
  },
  {
    id: "char-2",
    name: "Kael",
    role: "Nam chính",
    projectName: "Huyền Thoại Ánh Sáng",
    projectId: "proj-1",
    version: 1,
    isLocked: true,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1200&auto=format&fit=crop",
    description: "Chiến binh mang huyết thống rồng cổ, người nắm giữ thanh kiếm Quang Diệu.",
    gender: "Nam",
    age: 22,
    height: "182cm",
    hairColor: "Đen tuyền",
    eyeColor: "Xanh lam đậm",
    referenceAssets: [
      {
        id: "ref-k1",
        title: "Chân dung",
        imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
        type: "front",
      },
    ],
  },
  {
    id: "char-3",
    name: "Lyria",
    role: "Pháp sư",
    projectName: "Dòng Máu Rồng",
    projectId: "proj-2",
    version: 1,
    isLocked: false,
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1200&auto=format&fit=crop",
    description: "Pháp sư tinh linh bí ẩn từ rừng thẳm Valen, người có khả năng đọc các chòm sao.",
    gender: "Nữ",
    age: 24,
    height: "170cm",
    hairColor: "Xanh bóng đêm",
    eyeColor: "Hổ phách",
    referenceAssets: [],
  },
  {
    id: "char-4",
    name: "Darius",
    role: "Chiến binh",
    projectName: "Chiến Binh Cuối Cùng",
    projectId: "proj-5",
    version: 3,
    isLocked: true,
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1200&auto=format&fit=crop",
    description: "Đội trưởng cấm vệ quân dày dạn kinh nghiệm với hàng trăm chiến tích nơi sa trường.",
    gender: "Nam",
    age: 38,
    height: "188cm",
    hairColor: "Nâu sẫm",
    eyeColor: "Nâu hạt dẻ",
    referenceAssets: [],
  },
  {
    id: "char-5",
    name: "Valerius",
    role: "Phản diện",
    projectName: "Bí Ẩn Đảo Sương Mù",
    projectId: "proj-4",
    version: 1,
    isLocked: true,
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=1200&auto=format&fit=crop",
    description: "Lãnh chúa bóng tối ngự trị trên lâu đài sương mù vĩnh cửu.",
    gender: "Nam",
    age: 45,
    height: "185cm",
    hairColor: "Bạc xám",
    eyeColor: "Đỏ thẫm",
    referenceAssets: [],
  },
  {
    id: "char-6",
    name: "Seraphina",
    role: "Thánh nữ",
    projectName: "Ký Ức Vĩnh Hằng",
    projectId: "proj-6",
    version: 2,
    isLocked: false,
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1200&auto=format&fit=crop",
    description: "Người gìn giữ thư viện ký ức ngàn năm tại thủ phủ ánh sáng.",
    gender: "Nữ",
    age: 21,
    height: "168cm",
    hairColor: "Bạch kim",
    eyeColor: "Tím thạch anh",
    referenceAssets: [],
  },
  {
    id: "char-7",
    name: "Caelum",
    role: "Kỹ sư bay",
    projectName: "Thành Phố Nổi",
    projectId: "proj-7",
    version: 1,
    isLocked: true,
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1200&auto=format&fit=crop",
    description: "Nhà phát minh trẻ điều hành hệ thống đẩy phản trọng lực của thành phố trên mây.",
    gender: "Nam",
    age: 26,
    height: "178cm",
    hairColor: "Nâu hạt dẻ",
    eyeColor: "Xanh lam",
    referenceAssets: [],
  },
  {
    id: "char-8",
    name: "Morrigan",
    role: "Sát thủ bóng đêm",
    projectName: "Trái Tim Băng Giá",
    projectId: "proj-8",
    version: 2,
    isLocked: false,
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1200&auto=format&fit=crop",
    description: "Nữ thợ săn bí ẩn lướt qua bão tuyết phương Bắc không để lại dấu chân.",
    gender: "Nữ",
    age: 23,
    height: "172cm",
    hairColor: "Đen nhánh",
    eyeColor: "Xám tro",
    referenceAssets: [],
  },
];

export const MOCK_CHARACTERS: Character[] = MOCK_CHARACTER_SEEDS.map(
  ({ role, projectName, projectId, version, isLocked, ...character }) => ({
    ...character,
    canonicalIdentity: character.name,
    latestVersion: {
      versionNumber: version,
      status: isLocked ? "LOCKED" : "DRAFT",
    },
  })
);

export const MOCK_PROJECT_CHARACTERS: ProjectCharacter[] = MOCK_CHARACTER_SEEDS.map(
  ({ id: characterId, projectId, role, version, isLocked }) => ({
    id: `project-character-${projectId}-${characterId}`,
    projectId,
    characterId,
    role,
    importance: role === "Nữ chính" || role === "Nam chính" ? 1 : 0,
    projectAliases: [],
    groups: [],
    pinnedCharacterVersionId: isLocked ? `${characterId}-v${version}` : undefined,
    status: "ACTIVE",
  })
);

export const SAMPLE_STORY_PRESET = `Ngày xửa ngày xưa, tại vương quốc Eboria trù phú nằm giữa những dãy núi tuyết ngút ngàn và đại dương vô tận...

Ánh sáng và bóng tối đã tồn tại song hành từ thuở khai thiên lập địa. Truyền thuyết kể rằng viên ngọc Quang Diệu của Vương triều Ánh Sáng được cất giấu sâu trong Thánh Điện Eldoria. Khi các chòm sao hội tụ vào đêm nguyệt thực, cánh cổng phong ấn bóng tối ngàn năm dần hé mở.

Eleanor, nàng công chúa trẻ mang dòng máu ánh sáng, bước đi qua hành lang đá cẩm thạch rực rỡ của hoàng cung. Mái tóc vàng ánh kim phản chiếu ánh nến lung linh, đôi mắt xanh ngọc ánh lên niềm kiên định. Bên cạnh nàng, Kael - người hiệp sĩ trẻ trung thành với thanh kiếm rực lửa rồng - luôn cảnh giác trước từng bóng đen chuyển động.

"Đêm nay, sương mù từ phương Bắc đang tràn về thung lũng Valen nhanh hơn thường lệ," pháp sư Lyria cất giọng trầm ấm, bàn tay nhẹ lướt trên quả cầu tinh thể đang tỏa ánh lam huyền ảo.

Từ trên tháp canh thành trì, Darius - vị tướng dũng mãnh khoác trên mình bộ giáp nặng nề - gầm lên lệnh báo động. Cuộc hành trình tìm lại sự cân bằng cho vùng đất Eboria chính thức bắt đầu...`;
