import { Character, Project, ProjectCharacter, CharacterLifecycleStatus, CharacterRoleCategory } from "@/types/studio";

export type CharacterSeed = Omit<Character, "canonicalIdentity" | "latestVersion"> & {
  role: string;
  projectName: string;
  projectId: string;
  version: number;
  isLocked: boolean;
  status: CharacterLifecycleStatus;
  roleCategory: CharacterRoleCategory;
  group: string;
  appearancesCount: number;
  updatedAt: string;
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-tlk",
    title: "The Last Kingdom",
    name: "The Last Kingdom",
    description: "Cuộc chiến giành lại vương quốc cổ xưa và liên minh giữa các bộ tộc phương Bắc.",
    updatedAt: "1 giờ trước",
    progress: 65,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy / Epic",
    language: "Tiếng Anh / Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 42,
    locationCount: 22,
    chapterCount: 18,
    sceneCount: 96,
    visualBeatsCount: 180,
  },
  {
    id: "proj-ec",
    title: "Eclipse Chronicles",
    name: "Eclipse Chronicles",
    description: "Nhật thực vĩnh cửu bao phủ đế chế ngầm và hành trình tìm lại ánh sáng bình minh.",
    updatedAt: "3 giờ trước",
    progress: 45,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop",
    genre: "Sci-Fi / Fantasy",
    language: "Tiếng Anh / Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 28,
    locationCount: 14,
    chapterCount: 12,
    sceneCount: 72,
    visualBeatsCount: 140,
  },
  {
    id: "proj-btm",
    title: "Beyond The Mountains",
    name: "Beyond The Mountains",
    description: "Chuyến thám hiểm vượt rặng núi tuyết cấm địa khám phá nền văn minh đã mất.",
    updatedAt: "1 ngày trước",
    progress: 85,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop",
    genre: "Adventure",
    language: "Tiếng Anh / Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 18,
    locationCount: 11,
    chapterCount: 9,
    sceneCount: 54,
    visualBeatsCount: 110,
  },
  {
    id: "proj-1",
    title: "Huyền Thoại Ánh Sáng",
    name: "Huyền Thoại Ánh Sáng",
    description: "Câu chuyện về cuộc hành trình của một nhóm anh hùng chống lại thế lực bóng tối để khôi phục lại viên ngọc cổ đại.",
    updatedAt: "2 giờ trước",
    progress: 25,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 24,
    locationCount: 18,
    chapterCount: 15,
    sceneCount: 87,
    visualBeatsCount: 156,
  },
  {
    id: "proj-2",
    title: "Dòng Máu Rồng",
    name: "Dòng Máu Rồng",
    description: "Sự trỗi dậy của đế chế rồng ngàn năm và bí mật về vương triều bị lãng quên.",
    updatedAt: "1 ngày trước",
    progress: 80,
    isFavorite: true,
    coverImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 16,
    locationCount: 12,
    chapterCount: 10,
    sceneCount: 64,
    visualBeatsCount: 120,
  },
  {
    id: "proj-3",
    title: "Đường Về Nhà",
    name: "Đường Về Nhà",
    description: "Hành trình cô đơn qua những vùng đất hoang tàn của một lữ khách tìm lại quê hương.",
    updatedAt: "3 ngày trước",
    progress: 100,
    isFavorite: false,
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop",
    genre: "Sci-Fi",
    language: "Tiếng Việt",
    aspectRatio: "9:16",
    quality: "Standard",
    characterCount: 8,
    locationCount: 14,
    chapterCount: 8,
    sceneCount: 42,
    visualBeatsCount: 95,
  },
  {
    id: "proj-4",
    title: "Bí Ẩn Đảo Sương Mù",
    name: "Bí Ẩn Đảo Sương Mù",
    description: "Hòn đảo huyền bí xuất hiện giữa đại dương và lời nguyền của những thủy thủ mất tích.",
    updatedAt: "1 tuần trước",
    progress: 100,
    isFavorite: false,
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    genre: "Kinh dị",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 12,
    locationCount: 9,
    chapterCount: 6,
    sceneCount: 38,
    visualBeatsCount: 78,
  },
  {
    id: "proj-5",
    title: "Chiến Binh Cuối Cùng",
    name: "Chiến Binh Cuối Cùng",
    description: "Người bảo hộ cuối cùng của vương triều phương Bắc trong trận chiến định mệnh.",
    updatedAt: "1 ngày trước",
    progress: 50,
    isFavorite: false,
    coverImage: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop",
    genre: "Fantasy",
    language: "Tiếng Việt",
    aspectRatio: "16:9",
    quality: "High",
    characterCount: 19,
    locationCount: 15,
    chapterCount: 12,
    sceneCount: 70,
    visualBeatsCount: 135,
  },
];

export const MOCK_GROUPS = [
  { id: "grp-royal", name: "Royal Court", count: 18, description: "Hoàng gia Eldoria & Hội đồng nhiếp chính" },
  { id: "grp-knights", name: "Knights Guild", count: 24, description: "Hiệp sĩ đoàn bảo hộ vương quốc" },
  { id: "grp-shadow", name: "Shadow Order", count: 16, description: "Tổ chức sát thủ và điệp viên bóng đêm" },
  { id: "grp-mages", name: "Mage Circle", count: 20, description: "Hội pháp sư nguyên tố và nghiên cứu cổ thuật" },
  { id: "grp-explorers", name: "Explorers", count: 15, description: "Đoàn thám hiểm cấm địa phương Bắc" },
  { id: "grp-rebels", name: "Rebels", count: 12, description: "Liên minh kháng chiến tự do" },
];

export const MOCK_CHARACTER_SEEDS: CharacterSeed[] = [
  {
    id: "char-1",
    name: "Eleanor",
    role: "Nữ chính / Công chúa",
    roleCategory: "main",
    status: "IN_USE",
    group: "Royal Court",
    projectName: "The Last Kingdom",
    projectId: "proj-tlk",
    version: 3,
    isLocked: true,
    appearancesCount: 48,
    updatedAt: "10 phút trước",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1200&auto=format&fit=crop",
    description: "Nữ chính của câu chuyện, công chúa của vương quốc Eldoria, sở hữu sức mạnh ánh sáng cổ xưa truyền qua nhiều thế hệ.",
    gender: "Nữ",
    age: 19,
    height: "165cm",
    hairColor: "Vàng ánh kim",
    eyeColor: "Xanh ngọc",
    appearance: "Mái tóc vàng gợn sóng buông dài, đôi mắt ngọc lục bảo sắc sảo. Thường mặc lễ phục hoàng gia đính ngọc trai hoặc giáp bạc chiến trận nhẹ nhàng.",
    personality: "Kiên cường, quả cảm, giàu lòng trắc ẩn nhưng đôi khi quá nghiêm khắc với bản thân.",
    costume: "Trang phục chiến binh dạ quang Eldoria với đường nét thêu chỉ bạc và áo choàng lụa xanh sapphire.",
    relationships: "Đồng đội thân thiết với Kael, được Lyria bảo hộ pháp thuật, Darius là người thầy huấn luyện kiếm thuật.",
    referenceAssets: [
      {
        id: "ref-1",
        title: "Chân dung chính diện",
        imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
        type: "front",
      },
      {
        id: "ref-2",
        title: "Góc nghiêng 45 độ",
        imageUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop",
        type: "side",
      },
      {
        id: "ref-3",
        title: "Trang phục chiến trận",
        imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=400&auto=format&fit=crop",
        type: "costume",
      },
      {
        id: "ref-4",
        title: "Biểu cảm niệm chú",
        imageUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=400&auto=format&fit=crop",
        type: "expression",
      },
    ],
  },
  {
    id: "char-2",
    name: "Kael",
    role: "Nam chính / Hiệp sĩ rồng",
    roleCategory: "main",
    status: "IN_USE",
    group: "Knights Guild",
    projectName: "The Last Kingdom",
    projectId: "proj-tlk",
    version: 2,
    isLocked: true,
    appearancesCount: 42,
    updatedAt: "25 phút trước",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1200&auto=format&fit=crop",
    description: "Chiến binh mang huyết thống rồng cổ, người nắm giữ thanh kiếm Quang Diệu.",
    gender: "Nam",
    age: 22,
    height: "182cm",
    hairColor: "Đen tuyền",
    eyeColor: "Xanh lam đậm",
    referenceAssets: [
      {
        id: "ref-k1",
        title: "Chân dung",
        imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
        type: "front",
      },
    ],
  },
  {
    id: "char-3",
    name: "Lyria",
    role: "Pháp sư Tinh Linh",
    roleCategory: "supporting",
    status: "IN_USE",
    group: "Mage Circle",
    projectName: "Eclipse Chronicles",
    projectId: "proj-ec",
    version: 1,
    isLocked: false,
    appearancesCount: 29,
    updatedAt: "1 giờ trước",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=1200&auto=format&fit=crop",
    description: "Pháp sư tinh linh bí ẩn từ rừng thẳm Valen, người có khả năng đọc các chòm sao.",
    gender: "Nữ",
    age: 24,
    height: "170cm",
    hairColor: "Xanh bóng đêm",
    eyeColor: "Hổ phách",
    referenceAssets: [],
  },
  {
    id: "char-4",
    name: "Darius",
    role: "Thủ lĩnh Cấm Vệ Quân",
    roleCategory: "supporting",
    status: "IN_USE",
    group: "Knights Guild",
    projectName: "The Last Kingdom",
    projectId: "proj-tlk",
    version: 3,
    isLocked: true,
    appearancesCount: 35,
    updatedAt: "2 giờ trước",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1200&auto=format&fit=crop",
    description: "Đội trưởng cấm vệ quân dày dạn kinh nghiệm với hàng trăm chiến tích nơi sa trường.",
    gender: "Nam",
    age: 38,
    height: "188cm",
    hairColor: "Nâu sẫm",
    eyeColor: "Nâu hạt dẻ",
    referenceAssets: [],
  },
  {
    id: "char-5",
    name: "Valerius",
    role: "Lãnh chúa Hư Không",
    roleCategory: "main",
    status: "DRAFT",
    group: "Shadow Order",
    projectName: "Beyond The Mountains",
    projectId: "proj-btm",
    version: 1,
    isLocked: false,
    appearancesCount: 18,
    updatedAt: "4 giờ trước",
    avatarUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=1200&auto=format&fit=crop",
    description: "Lãnh chúa bóng tối ngự trị trên lâu đài sương mù vĩnh cửu.",
    gender: "Nam",
    age: 45,
    height: "185cm",
    hairColor: "Bạc xám",
    eyeColor: "Đỏ thẫm",
    referenceAssets: [],
  },
  {
    id: "char-6",
    name: "Seraphina",
    role: "Thánh nữ Tri Thức",
    roleCategory: "supporting",
    status: "IN_USE",
    group: "Royal Court",
    projectName: "Eclipse Chronicles",
    projectId: "proj-ec",
    version: 2,
    isLocked: true,
    appearancesCount: 22,
    updatedAt: "6 giờ trước",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1200&auto=format&fit=crop",
    description: "Người gìn giữ thư viện ký ức ngàn năm tại thủ phủ ánh sáng.",
    gender: "Nữ",
    age: 21,
    height: "168cm",
    hairColor: "Bạch kim",
    eyeColor: "Tím thạch anh",
    referenceAssets: [],
  },
  {
    id: "char-7",
    name: "Caelum",
    role: "Kỹ sư Thám Hiểm",
    roleCategory: "supporting",
    status: "DRAFT",
    group: "Explorers",
    projectName: "Beyond The Mountains",
    projectId: "proj-btm",
    version: 1,
    isLocked: false,
    appearancesCount: 14,
    updatedAt: "1 ngày trước",
    avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=1200&auto=format&fit=crop",
    description: "Nhà phát minh trẻ điều hành hệ thống đẩy phản trọng lực của thành phố trên mây.",
    gender: "Nam",
    age: 26,
    height: "178cm",
    hairColor: "Nâu hạt dẻ",
    eyeColor: "Xanh lam",
    referenceAssets: [],
  },
  {
    id: "char-8",
    name: "Morrigan",
    role: "Sát thủ Phương Bắc",
    roleCategory: "main",
    status: "ARCHIVED",
    group: "Shadow Order",
    projectName: "Eclipse Chronicles",
    projectId: "proj-ec",
    version: 2,
    isLocked: true,
    appearancesCount: 31,
    updatedAt: "2 ngày trước",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1200&auto=format&fit=crop",
    description: "Nữ thợ săn bí ẩn lướt qua bão tuyết phương Bắc không để lại dấu chân.",
    gender: "Nữ",
    age: 23,
    height: "172cm",
    hairColor: "Đen nhánh",
    eyeColor: "Xám tro",
    referenceAssets: [],
  },
  {
    id: "char-9",
    name: "Theron",
    role: "Quân sư Hoàng Gia",
    roleCategory: "supporting",
    status: "IN_USE",
    group: "Royal Court",
    projectName: "The Last Kingdom",
    projectId: "proj-tlk",
    version: 1,
    isLocked: true,
    appearancesCount: 26,
    updatedAt: "3 ngày trước",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=1200&auto=format&fit=crop",
    description: "Quân sư trưởng với trí tuệ uyên bác điều phối toàn bộ chiến lược phòng thủ biên giới.",
    gender: "Nam",
    age: 42,
    height: "176cm",
    hairColor: "Muối tiêu",
    eyeColor: "Nâu sẫm",
    referenceAssets: [],
  },
  {
    id: "char-10",
    name: "Astrid",
    role: "Nữ Cung Thủ Tuyết",
    roleCategory: "minor",
    status: "IN_USE",
    group: "Explorers",
    projectName: "Beyond The Mountains",
    projectId: "proj-btm",
    version: 1,
    isLocked: false,
    appearancesCount: 11,
    updatedAt: "4 ngày trước",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=1200&auto=format&fit=crop",
    description: "Cung thủ lão luyện có khả năng bắn trúng hồng tâm từ khoảng cách hàng trăm mét trong bão tuyết.",
    gender: "Nữ",
    age: 20,
    height: "167cm",
    hairColor: "Nâu sáng",
    eyeColor: "Xanh lá",
    referenceAssets: [],
  },
  {
    id: "char-11",
    name: "Ragnar",
    role: "Chiến binh Cuồng nộ",
    roleCategory: "minor",
    status: "ARCHIVED",
    group: "Knights Guild",
    projectName: "The Last Kingdom",
    projectId: "proj-tlk",
    version: 1,
    isLocked: false,
    appearancesCount: 8,
    updatedAt: "5 ngày trước",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=1200&auto=format&fit=crop",
    description: "Dũng sĩ tiền tuyến mang song búa khổng lồ càn quét đội hình quân địch.",
    gender: "Nam",
    age: 32,
    height: "192cm",
    hairColor: "Hung đỏ",
    eyeColor: "Xanh xám",
    referenceAssets: [],
  },
  {
    id: "char-12",
    name: "Sylvia",
    role: "Y giả Tinh Vân",
    roleCategory: "minor",
    status: "DRAFT",
    group: "Mage Circle",
    projectName: "Eclipse Chronicles",
    projectId: "proj-ec",
    version: 1,
    isLocked: false,
    appearancesCount: 6,
    updatedAt: "1 tuần trước",
    avatarUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=600&auto=format&fit=crop",
    fullPortraitUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=1200&auto=format&fit=crop",
    description: "Y giả thảo dược có khả năng thanh tẩy vết thương do ma thuật hắc ám gây ra.",
    gender: "Nữ",
    age: 22,
    height: "162cm",
    hairColor: "Nâu mật ong",
    eyeColor: "Hạt dẻ",
    referenceAssets: [],
  },
];

export const MOCK_CHARACTERS: Character[] = MOCK_CHARACTER_SEEDS.map(
  ({ role, projectName, projectId, version, isLocked, ...character }) => ({
    ...character,
    canonicalIdentity: character.name,
    latestVersion: {
      versionNumber: version,
      status: isLocked ? "LOCKED" : "DRAFT",
    },
  })
);

export const MOCK_PROJECT_CHARACTERS: ProjectCharacter[] = MOCK_CHARACTER_SEEDS.map(
  ({ id: characterId, projectId, role, version, isLocked, group }) => ({
    id: `project-character-${projectId}-${characterId}`,
    projectId,
    characterId,
    role,
    importance: role.includes("Nữ chính") || role.includes("Nam chính") || role.includes("main") ? 1 : 0,
    projectAliases: [],
    groups: group ? [group] : [],
    pinnedCharacterVersionId: isLocked ? `${characterId}-v${version}` : undefined,
    status: "ACTIVE",
  })
);

export const SAMPLE_STORY_PRESET = `Ngày xửa ngày xưa, tại vương quốc Eboria trù phú nằm giữa những dãy núi tuyết ngút ngàn và đại dương vô tận...

Ánh sáng và bóng tối đã tồn tại song hành từ thuở khai thiên lập địa. Truyền thuyết kể rằng viên ngọc Quang Diệu của Vương triều Ánh Sáng được cất giấu sâu trong Thánh Điện Eldoria. Khi các chòm sao hội tụ vào đêm nguyệt thực, cánh cổng phong ấn bóng tối ngàn năm dần hé mở.

Eleanor, nàng công chúa trẻ mang dòng máu ánh sáng, bước đi qua hành lang đá cẩm thạch rực rỡ của hoàng cung. Mái tóc vàng ánh kim phản chiếu ánh nến lung linh, đôi mắt xanh ngọc ánh lên niềm kiên định. Bên cạnh nàng, Kael - người hiệp sĩ trẻ trung thành với thanh kiếm rực lửa rồng - luôn cảnh giác trước từng bóng đen chuyển động.

"Đêm nay, sương mù từ phương Bắc đang tràn về thung lũng Valen nhanh hơn thường lệ," pháp sư Lyria cất giọng trầm ấm, bàn tay nhẹ lướt trên quả cầu tinh thể đang tỏa ánh lam huyền ảo.

Từ trên tháp canh thành trì, Darius - vị tướng dũng mãnh khoác trên mình bộ giáp nặng nề - gầm lên lệnh báo động. Cuộc hành trình tìm lại sự cân bằng cho vùng đất Eboria chính thức bắt đầu...`;
