import { StylePreset } from "@/types/presets";

export const MOCK_PRESETS: StylePreset[] = [
  // 1. Visual Styles
  {
    id: "style-1",
    name: "Cinematic Dark Fantasy",
    category: "VISUAL_STYLE",
    isDefault: true,
    description: "Đậm chất điện ảnh, tông tối, ánh sáng kịch tính, phù hợp với truyện kiếm hiệp, fantasy.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    tags: ["CINEMATIC", "DARK", "FANTASY"],
    usedInProjectsCount: 8,
    colorPalette: ["#070B14", "#111A29", "#7C3AED", "#D97706", "#94A3B8"],
    lighting: "Kịch tính, tương phản cao, ánh sáng định hướng",
    atmosphere: "Huyền bí, u tối, mạnh mẽ",
    cameraStyle: "35mm cinematic, shallow DOF, dynamic angles",
    defaultAspectRatio: "16:9",
    defaultQuality: "STANDARD",
    motionPreset: "Slow pan, dramatic zoom, smooth motion",
    negativeRules: "No text, no watermark, no distorted anatomy, no low quality",
    usedInProjects: [
      {
        id: "proj-1",
        title: "Huyền Thoại Kiếm Thần",
        chaptersCount: 10,
        coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=300&auto=format&fit=crop",
      },
      {
        id: "proj-2",
        title: "Hành Trình Ma Kiếm",
        chaptersCount: 6,
        coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=300&auto=format&fit=crop",
      },
      {
        id: "proj-3",
        title: "Chiến Thần Trở Lại",
        chaptersCount: 8,
        coverImage: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=300&auto=format&fit=crop",
      },
    ],
  },
  {
    id: "style-2",
    name: "Wuxia Epic",
    category: "VISUAL_STYLE",
    description: "Phong cách kiếm hiệp cổ trang, tông màu tự nhiên, rộng lớn, giàu cảm xúc.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    tags: ["WUXIA", "EPIC", "NATURAL"],
    usedInProjectsCount: 5,
    colorPalette: ["#14241B", "#274834", "#4ADE80", "#EAB308", "#E2E8F0"],
    lighting: "Ánh sáng tự nhiên buổi sáng, sương mờ núi rừng",
    atmosphere: "Hùng vĩ, lãng đãng kiếm hiệp, thanh tao",
    cameraStyle: "Wide landscape, sweeping aerial crane shots",
    defaultAspectRatio: "16:9",
    defaultQuality: "High",
    motionPreset: "Sweeping pan, gentle breeze motion",
    negativeRules: "No modern elements, no guns, no cars, no low quality",
    usedInProjects: [
      {
        id: "proj-4",
        title: "Dòng Máu Rồng",
        chaptersCount: 12,
        coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=300&auto=format&fit=crop",
      },
    ],
  },
  {
    id: "style-3",
    name: "Cyberpunk Night",
    category: "VISUAL_STYLE",
    description: "Thành phố tương lai, ánh sáng neon, phản chiếu, bầu không khí hiện đại.",
    coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop",
    tags: ["CYBERPUNK", "NEON", "FUTURISTIC"],
    usedInProjectsCount: 5,
    colorPalette: ["#0B0D1B", "#1E1B4B", "#EC4899", "#06B6D4", "#F43F5E"],
    lighting: "Neon rực rỡ, phản chiếu mặt đường ướt mưa, backlight",
    atmosphere: "Tối tăm công nghệ cao, sôi động, nghẹt thở",
    cameraStyle: "Dutch angles, close-up anamorphic lens",
    defaultAspectRatio: "16:9",
    defaultQuality: "High",
    motionPreset: "Fast tracking, chromatic glitch zoom",
    negativeRules: "No vintage paper, no swords, no low resolution",
    usedInProjects: [
      {
        id: "proj-5",
        title: "Ký Ức Vĩnh Hằng",
        chaptersCount: 14,
        coverImage: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=300&auto=format&fit=crop",
      },
    ],
  },
  {
    id: "style-4",
    name: "Animated Fantasy",
    category: "VISUAL_STYLE",
    description: "Phong cách hoạt hình cao cấp, màu sắc tươi sáng, phù hợp truyện thiếu nhi và anime.",
    coverImage: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop",
    tags: ["ANIME", "COLORFUL", "FANTASY"],
    usedInProjectsCount: 2,
    colorPalette: ["#1E1B4B", "#4338CA", "#38BDF8", "#F472B6", "#FDE047"],
    lighting: "Ánh sáng dịu nhẹ, anime cel-shading, rực rỡ",
    atmosphere: "Mộng mơ, trong trẻo, phiêu lưu kỳ thú",
    cameraStyle: "Clean anime framing, high dynamic motion shots",
    defaultAspectRatio: "16:9",
    defaultQuality: "High",
    motionPreset: "Parallax layers, anime action zoom",
    negativeRules: "No realistic photorealism, no 3D render look",
    usedInProjects: [],
  },
  {
    id: "style-5",
    name: "Noir Monochrome",
    category: "VISUAL_STYLE",
    description: "Đen trắng tương phản cao, cảm giác bí ẩn, trinh thám, cổ điển.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    tags: ["NOIR", "MONO", "MYSTERY"],
    usedInProjectsCount: 1,
    colorPalette: ["#000000", "#18181B", "#52525B", "#A1A1AA", "#FFFFFF"],
    lighting: "Chiaroscuro, tương phản gắt, bóng đổ sắc nét",
    atmosphere: "Lạnh lùng, hoài nghi, trinh thám ly kỳ",
    cameraStyle: "50mm prime, deep shadows, low angles",
    defaultAspectRatio: "16:9",
    defaultQuality: "Standard",
    motionPreset: "Slow deliberate pan, static tension",
    negativeRules: "No color, no bright saturation, no cartoon style",
    usedInProjects: [],
  },

  // 2. Image Presets
  {
    id: "img-preset-1",
    name: "Cinematic 16:9 Wide Shot",
    category: "IMAGE",
    description: "Khung cảnh đại cảnh góc rộng tỷ lệ điện ảnh 16:9 với chiều sâu bối cảnh xuất sắc.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    tags: ["16:9", "WIDE", "CINEMA"],
    usedInProjectsCount: 15,
    defaultAspectRatio: "16:9",
    defaultQuality: "High",
    cameraStyle: "24mm ultra-wide master shot",
  },
  {
    id: "img-preset-2",
    name: "Portrait Character Master",
    category: "IMAGE",
    description: "Chân dung cận cảnh nhân vật tỷ lệ 2:3 phục vụ tạo Character Bible sắc nét.",
    coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
    tags: ["2:3", "PORTRAIT", "CHARACTER"],
    usedInProjectsCount: 12,
    defaultAspectRatio: "2:3",
    defaultQuality: "Master",
    cameraStyle: "85mm f/1.4 portrait prime lens",
  },
  {
    id: "img-preset-3",
    name: "Vertical Shorts 9:16",
    category: "IMAGE",
    description: "Cấu hình khung hình dọc 9:16 tối ưu cho video ngắn TikTok, Reels và Shorts.",
    coverImage: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop",
    tags: ["9:16", "SHORTS", "TIKTOK"],
    usedInProjectsCount: 9,
    defaultAspectRatio: "9:16",
    defaultQuality: "Standard",
  },

  // 3. Motion Presets
  {
    id: "motion-preset-1",
    name: "Slow Cinematic Pan",
    category: "MOTION",
    description: "Lia máy quay chậm từ trái sang phải tạo cảm giác không gian bao la rộng lớn.",
    coverImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800&auto=format&fit=crop",
    tags: ["SLOW", "PAN", "CINEMA"],
    usedInProjectsCount: 8,
    motionType: "Horizontal Pan",
    motionIntensity: "Slow (0.2x)",
    motionEasing: "Smooth In-Out",
  },
  {
    id: "motion-preset-2",
    name: "Dramatic Zoom In",
    category: "MOTION",
    description: "Phóng to chậm vào biểu cảm nhân vật hoặc chi tiết mấu chốt tăng kịch tính.",
    coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
    tags: ["ZOOM", "DRAMA", "FOCUS"],
    usedInProjectsCount: 6,
    motionType: "Slow Zoom",
    motionIntensity: "Medium (0.4x)",
  },

  // 4. Outfit Presets
  {
    id: "outfit-preset-1",
    name: "Royal Fantasy Circlet",
    category: "OUTFIT",
    description: "Trang phục hoàng gia đính ngọc quý, áo choàng nhung viền vàng lấp lánh.",
    coverImage: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
    tags: ["ROYAL", "FANTASY", "GOLD"],
    usedInProjectsCount: 4,
    outfitTheme: "Royal Court",
    outfitDetails: "Gold-trimmed velvet cloak, emerald circlet, silk tunic",
  },
  {
    id: "outfit-preset-2",
    name: "Winter Expedition Fur Armor",
    category: "OUTFIT",
    description: "Áo giáp da kết hợp lông thú dày phục vụ các trường đoạn hành quân phương Bắc.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    tags: ["WINTER", "ARMOR", "EXPEDITION"],
    usedInProjectsCount: 6,
    outfitTheme: "North Expedition",
    outfitDetails: "Heavy fur collar, hardened leather pauldrons, steel gauntlets",
  },

  // 5. Render Presets
  {
    id: "render-preset-1",
    name: "YouTube Long-form 1080p Master",
    category: "RENDER",
    description: "Cấu hình xuất video full HD 1080p, bitrate cao, phụ đề tự động cho YouTube.",
    coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    tags: ["1080P", "YOUTUBE", "HIGH_BITRATE"],
    usedInProjectsCount: 10,
    renderResolution: "1080p (Full HD)",
    renderBitrate: "16 Mbps High",
  },
  {
    id: "render-preset-2",
    name: "TikTok / Shorts 9:16 Dynamic",
    category: "RENDER",
    description: "Cấu hình xuất video ngắn dọc 9:16 kèm phụ đề nổi bật cho mạng xã hội.",
    coverImage: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop",
    tags: ["9:16", "TIKTOK", "REELS"],
    usedInProjectsCount: 8,
    renderResolution: "1080x1920 (Vertical)",
    renderBitrate: "12 Mbps",
  },
];
