import { Chapter, ProjectProductionDetail, Scene, VisualBeat } from "@/types/domain";

export const MOCK_VISUAL_BEATS_CH06: VisualBeat[] = [
  {
    id: "beat-1",
    number: 1,
    sceneId: "scene-1",
    chapterId: "ch-06",
    prompt: "EXT. THÀNH HẮC VÂN - SÁNG SỚM. Dark gothic castle gate opening with armoured knights marching into thick mountain fog, cinematic rim lighting, 8k octane render",
    description: "EXT. THÀNH HẮC VÂN - SÁNG SỚM",
    status: "APPROVED",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 12,
    cameraMovement: "Slow push-in",
    lighting: "Cold morning atmospheric rim",
  },
  {
    id: "beat-2",
    number: 2,
    sceneId: "scene-1",
    chapterId: "ch-06",
    prompt: "ĐOÀN QUÂN XUẤT PHÁT. A vanguard of silver-armored warriors on horseback crossing an icy bridge, glowing banner in twilight, ultra realistic",
    description: "ĐOÀN QUÂN XUẤT PHÁT",
    status: "APPROVED",
    imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 14,
    cameraMovement: "Wide tracking pan",
    lighting: "Twilight blue hour",
  },
  {
    id: "beat-3",
    number: 3,
    sceneId: "scene-2",
    chapterId: "ch-06",
    prompt: "ĐƯỜNG NÚI TUYẾT. Steep mountain pass covered in heavy blizzard snow, lone warrior silhouette guiding the troops through treacherous cliffs",
    description: "ĐƯỜNG NÚI TUYẾT",
    status: "APPROVED",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 10,
    cameraMovement: "Low angle tilt",
    lighting: "Harsh blizzard storm highlights",
  },
  {
    id: "beat-4",
    number: 4,
    sceneId: "scene-2",
    chapterId: "ch-06",
    prompt: "BÃO TUYẾT ẬP ĐẾN. Intense vortex of snow swirling around ancient frozen monoliths, dark shadows creeping behind ice pillars",
    description: "BÃO TUYẾT ẬP ĐẾN",
    status: "NEEDS_REVIEW",
    imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 15,
    cameraMovement: "Dynamic shake zoom",
    lighting: "Deep violet shadow contrast",
  },
  {
    id: "beat-5",
    number: 5,
    sceneId: "scene-3",
    chapterId: "ch-06",
    prompt: "SINH VẬT BĂNG GIÁ. Colossal frost golem emerging from glacial crevices with glowing blue ice core eyes, terrifying scale",
    description: "SINH VẬT BĂNG GIÁ",
    status: "APPROVED",
    imageUrl: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 18,
    cameraMovement: "Extreme wide upward crane",
    lighting: "Arcane cyan glow",
  },
  {
    id: "beat-6",
    number: 6,
    sceneId: "scene-3",
    chapterId: "ch-06",
    prompt: "GIAO CHIẾN. Knight with flaming radiant sword clashing against icy claws, sparks flying in subzero gale, epic cinematic composition",
    description: "GIAO CHIẾN",
    status: "NEEDS_REVIEW",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 12,
    cameraMovement: "Rapid orbit tracking",
    lighting: "Fiery orange and ice blue dual contrast",
  },
  {
    id: "beat-7",
    number: 7,
    sceneId: "scene-4",
    chapterId: "ch-06",
    prompt: "THIÊN BĂNG KÍCH. Ice shards erupting from the ground, character consistency mismatch in armor detail",
    description: "THIÊN BĂNG KÍCH",
    status: "REJECTED",
    imageUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 8,
    cameraMovement: "Static medium shot",
    lighting: "Overexposed backlight",
  },
  {
    id: "beat-8",
    number: 8,
    sceneId: "scene-4",
    chapterId: "ch-06",
    prompt: "RÚT LUI CHIẾN THUẬT. Scouting party taking shelter inside an ancient crystal cavern, torches flickering against ice walls",
    description: "RÚT LUI CHIẾN THUẬT",
    status: "APPROVED",
    imageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=600&auto=format&fit=crop",
    durationSeconds: 14,
    cameraMovement: "Smooth dolly in",
    lighting: "Warm torchlight on crystal reflections",
  },
];

export const MOCK_SCENES_CH06: Scene[] = [
  {
    id: "scene-1",
    number: "01",
    title: "Rời khỏi Hắc Vân",
    chapterId: "ch-06",
    beatsCount: 3,
    approvedBeatsCount: 2,
    thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop",
    status: "READY",
  },
  {
    id: "scene-2",
    number: "02",
    title: "Giữa cơn bão tuyết",
    chapterId: "ch-06",
    beatsCount: 4,
    approvedBeatsCount: 4,
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop",
    status: "READY",
  },
  {
    id: "scene-3",
    number: "03",
    title: "Sinh vật băng giá",
    chapterId: "ch-06",
    beatsCount: 3,
    approvedBeatsCount: 3,
    thumbnail: "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop",
    status: "READY",
  },
  {
    id: "scene-4",
    number: "04",
    title: "Do thám địch",
    chapterId: "ch-06",
    beatsCount: 5,
    approvedBeatsCount: 5,
    thumbnail: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop",
    status: "READY",
  },
  {
    id: "scene-5",
    number: "05",
    title: "Thung Lũng Gió Hú",
    chapterId: "ch-06",
    beatsCount: 4,
    approvedBeatsCount: 3,
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop",
    status: "READY",
  },
  {
    id: "scene-6",
    number: "06",
    title: "Đền Thờ Băng Cổ",
    chapterId: "ch-06",
    beatsCount: 6,
    approvedBeatsCount: 4,
    thumbnail: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop",
    status: "READY",
  },
];

export const MOCK_CHAPTERS: Chapter[] = [
  {
    id: "ch-01",
    number: "01",
    title: "Khởi đầu",
    status: "RENDERED",
    scenesCount: 12,
    duration: "06:12",
    lastUpdated: "17/08/2026 10:30",
    progressPercent: 100,
    generatedVisualsCount: 32,
    totalVisualsCount: 32,
    scenes: [],
    storyExcerpt: "Thiếu niên rời khỏi ngôi làng nhỏ dưới chân núi với thanh đoản kiếm rỉ sét...",
  },
  {
    id: "ch-02",
    number: "02",
    title: "Bí mật cổ kiếm",
    status: "RENDERED",
    scenesCount: 14,
    duration: "07:48",
    lastUpdated: "17/08/2026 08:15",
    progressPercent: 100,
    generatedVisualsCount: 36,
    totalVisualsCount: 36,
    scenes: [],
    storyExcerpt: "Bên trong hang động ngầm, ánh sáng xanh lục hé lộ ký tự cổ xưa khắc trên thân kiếm...",
  },
  {
    id: "ch-03",
    number: "03",
    title: "Cuộc truy sát",
    status: "VISUAL_REVIEW",
    scenesCount: 16,
    duration: "08:10",
    lastUpdated: "17/08/2026 11:45",
    progressPercent: 75,
    generatedVisualsCount: 40,
    totalVisualsCount: 44,
    scenes: [],
    storyExcerpt: "Những bóng đen cưỡi sói tuyết lao qua cánh rừng thông trong đêm nguyệt thực...",
  },
  {
    id: "ch-04",
    number: "04",
    title: "Thành Hắc Vân",
    status: "ANALYZED",
    scenesCount: 12,
    duration: "05:42",
    lastUpdated: "16/08/2026 22:20",
    progressPercent: 30,
    generatedVisualsCount: 0,
    totalVisualsCount: 30,
    scenes: [],
    storyExcerpt: "Pháo đài sừng sững giữa biển mây đen u ám, nơi các gia tộc ngầm chia cắt quyền lực...",
  },
  {
    id: "ch-05",
    number: "05",
    title: "Đại chiến",
    status: "DRAFT",
    scenesCount: 0,
    duration: "00:00",
    lastUpdated: "16/08/2026 18:00",
    progressPercent: 0,
    generatedVisualsCount: 0,
    totalVisualsCount: 0,
    scenes: [],
    storyExcerpt: "Hai đạo quân dàn trận trên đồng bằng hoang tàn, tiếng trống trận rung chuyển trời đất...",
  },
  {
    id: "ch-06",
    number: "06",
    title: "Cuộc hành quân đến phương Bắc",
    status: "GENERATING_VISUALS",
    scenesCount: 14,
    duration: "07:36",
    lastUpdated: "17/08/2026 14:45",
    progressPercent: 84,
    generatedVisualsCount: 32,
    totalVisualsCount: 38,
    scenes: MOCK_SCENES_CH06,
    storyExcerpt: "Đoàn quân rời khỏi thành Hắc Vân trong sương sớm, hướng về phương Bắc lạnh giá. Trên con đường phủ đầy tuyết trắng, họ phải đối mặt với những sinh vật huyền bí và băng giá khắc nghiệt...",
  },
  {
    id: "ch-07",
    number: "07",
    title: "Chưa nhập nội dung",
    status: "EMPTY",
    scenesCount: 0,
    duration: "00:00",
    lastUpdated: "—",
    progressPercent: 0,
    generatedVisualsCount: 0,
    totalVisualsCount: 0,
    scenes: [],
  },
  {
    id: "ch-08",
    number: "08",
    title: "Chưa nhập nội dung",
    status: "EMPTY",
    scenesCount: 0,
    duration: "00:00",
    lastUpdated: "—",
    progressPercent: 0,
    generatedVisualsCount: 0,
    totalVisualsCount: 0,
    scenes: [],
  },
  {
    id: "ch-09",
    number: "09",
    title: "Chưa nhập nội dung",
    status: "EMPTY",
    scenesCount: 0,
    duration: "00:00",
    lastUpdated: "—",
    progressPercent: 0,
    generatedVisualsCount: 0,
    totalVisualsCount: 0,
    scenes: [],
  },
  {
    id: "ch-10",
    number: "10",
    title: "Chưa nhập nội dung",
    status: "EMPTY",
    scenesCount: 0,
    duration: "00:00",
    lastUpdated: "—",
    progressPercent: 0,
    generatedVisualsCount: 0,
    totalVisualsCount: 0,
    scenes: [],
  },
];

export const MOCK_PROJECT_PRODUCTION: ProjectProductionDetail = {
  id: "proj-kiem-than",
  title: "Huyền Thoại Kiếm Thần",
  planBadge: "PRO",
  description: "Hành trình của thiếu niên tìm kiếm thanh kiếm huyền thoại để cứu vương quốc.",
  createdAt: "13/08/2026",
  updatedAt: "17/08/2026",
  coverImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop",
  totalChapters: 10,
  readyChapters: 6,
  renderedChapters: 4,
  processingJobs: 2,
  estimatedDuration: "58:42",
  totalScenes: 126,
  approvedVisuals: 184,
  overallProgress: 60,
  chapters: MOCK_CHAPTERS,
};
