-- NarrativeX consolidated PostgreSQL/Flyway baseline schema.
-- PostgreSQL is authoritative; Redis remains an acceleration layer only.

-- -----------------------------------------------------------------------------
-- Baseline marker
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS schema_baseline (
    id VARCHAR(64) PRIMARY KEY,
    initialized_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);

INSERT INTO schema_baseline (id, description)
VALUES ('v1_baseline', 'NarrativeX consolidated schema baseline')
ON CONFLICT (id) DO NOTHING;

-- -----------------------------------------------------------------------------
-- Authentication & Users
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS auth_users (
    id VARCHAR(128) PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    display_name VARCHAR(160) NOT NULL,
    avatar_url TEXT,
    password_hash VARCHAR(255),
    google_subject VARCHAR(255) UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Durable domain foundation (Projects, Stories, Chapters, Scenes, Visual Beats)
-- -----------------------------------------------------------------------------

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    cover_image_url VARCHAR(1024),
    owner_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    source_language VARCHAR(16) NOT NULL,
    narration_language VARCHAR(16) NOT NULL,
    metadata_language VARCHAR(16) NOT NULL,
    image_aspect_ratio VARCHAR(16) NOT NULL,
    image_quality_tier VARCHAR(16) NOT NULL,
    archived_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_projects_status CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);
CREATE INDEX idx_projects_owner_status ON projects (owner_id, status);
CREATE INDEX idx_projects_owner_updated_id ON projects (owner_id, updated_at DESC, id DESC);
CREATE INDEX idx_projects_active_owner_updated_id
    ON projects (owner_id, updated_at DESC, id DESC)
    WHERE archived_at IS NULL;

CREATE TABLE story_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    version_number INTEGER NOT NULL,
    content TEXT NOT NULL,
    source_language VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    moderation_decision VARCHAR(16) NOT NULL,
    CONSTRAINT uk_story_versions_project_version UNIQUE (project_id, version_number),
    CONSTRAINT ck_story_versions_status
        CHECK (status IN ('DRAFT', 'ACTIVE', 'SUPERSEDED', 'BLOCKED')),
    CONSTRAINT ck_story_versions_moderation_decision
        CHECK (moderation_decision IN ('PENDING', 'SAFE', 'REVIEW', 'BLOCK'))
);

CREATE UNIQUE INDEX uq_story_versions_one_active_per_project
    ON story_versions (project_id)
    WHERE status = 'ACTIVE';

CREATE TABLE chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    story_version_id BIGINT NOT NULL REFERENCES story_versions(id),
    order_index INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    source_text TEXT NOT NULL,
    source_hash VARCHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    estimated_duration_ms BIGINT,
    generation_progress INTEGER NOT NULL DEFAULT 0,
    source_story_version_id BIGINT REFERENCES story_versions(id),
    inherited_snapshot_hash VARCHAR(128),
    CONSTRAINT uk_chapters_story_order UNIQUE (story_version_id, order_index),
    CONSTRAINT ck_chapters_source_hash_sha256 CHECK (source_hash ~ '^[0-9a-f]{64}$')
);

CREATE TABLE scenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chapter_id BIGINT NOT NULL REFERENCES chapters(id),
    order_index INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    narration TEXT,
    duration_seconds INTEGER,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    CONSTRAINT uk_scenes_chapter_order UNIQUE (chapter_id, order_index)
);
CREATE INDEX idx_scenes_chapter_status ON scenes (chapter_id, status);

CREATE TABLE visual_beats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    scene_id BIGINT NOT NULL REFERENCES scenes(id),
    order_index INTEGER NOT NULL,
    visual_intent TEXT NOT NULL,
    motion_action VARCHAR(24) NOT NULL,
    aspect_ratio_override VARCHAR(16),
    quality_tier_override VARCHAR(16),
    CONSTRAINT uk_visual_beats_scene_order UNIQUE (scene_id, order_index)
);

CREATE TABLE generation_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    job_id VARCHAR(36) NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    job_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    resource_class VARCHAR(32) NOT NULL,
    progress INTEGER NOT NULL,
    current_step VARCHAR(80),
    error_code VARCHAR(80),
    requested_by_user_id VARCHAR(128) NOT NULL,
    billed_to_user_id VARCHAR(128) NOT NULL,
    story_version_id BIGINT REFERENCES story_versions(id),
    chapter_id BIGINT REFERENCES chapters(id),
    chapter_row_version BIGINT,
    source_hash VARCHAR(64),
    source_text TEXT,
    source_language VARCHAR(16),
    idempotency_key VARCHAR(200)
);
CREATE UNIQUE INDEX uq_generation_jobs_idempotency_key
    ON generation_jobs (idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_generation_jobs_chapter_created
    ON generation_jobs (chapter_id, created_at DESC)
    WHERE chapter_id IS NOT NULL;
CREATE INDEX idx_generation_jobs_project_status
    ON generation_jobs (project_id, status);

CREATE TABLE stage_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    generation_job_id BIGINT NOT NULL REFERENCES generation_jobs(id),
    stage_name VARCHAR(64) NOT NULL,
    attempt_number INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    worker_id VARCHAR(128),
    heartbeat_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_stage_attempts_job_stage_number UNIQUE (generation_job_id, stage_name, attempt_number)
);
CREATE INDEX idx_stage_attempts_claimable
    ON stage_attempts (status, created_at, id)
    WHERE status IN ('QUEUED', 'STALLED');

CREATE TABLE provider_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    stage_attempt_id BIGINT NOT NULL REFERENCES stage_attempts(id),
    provider_key VARCHAR(64) NOT NULL,
    provider_operation_id VARCHAR(256),
    status VARCHAR(32) NOT NULL,
    reserved_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE operation_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    operation_type VARCHAR(40) NOT NULL,
    estimate_min NUMERIC(19, 6) NOT NULL,
    estimate_max NUMERIC(19, 6) NOT NULL,
    max_authorized_cost NUMERIC(19, 6) NOT NULL,
    confidence VARCHAR(16) NOT NULL
);

-- -----------------------------------------------------------------------------
-- Control plane, moderation, preferences, audit & policies
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS moderation_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128),
    project_id BIGINT REFERENCES projects(id),
    entity_type VARCHAR(48) NOT NULL,
    entity_id VARCHAR(128) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    result VARCHAR(16) NOT NULL,
    categories_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    provider_signal_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    policy_version VARCHAR(64) NOT NULL,
    reviewer_id VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_moderation_entity ON moderation_decisions (entity_type, entity_id, created_at DESC);

CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id VARCHAR(128) PRIMARY KEY,
    render_complete_email BOOLEAN NOT NULL DEFAULT FALSE,
    render_failed_email BOOLEAN NOT NULL DEFAULT FALSE,
    short_complete_email BOOLEAN NOT NULL DEFAULT FALSE,
    web_push_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    row_version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    project_id BIGINT REFERENCES projects(id),
    event_key VARCHAR(160) NOT NULL UNIQUE,
    type VARCHAR(48) NOT NULL,
    channel_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    title_key VARCHAR(128) NOT NULL,
    message_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications (user_id, read_at, created_at DESC);

CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    event_key VARCHAR(160) NOT NULL UNIQUE,
    payload_json JSONB NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON outbox_events (status, available_at);

CREATE TABLE IF NOT EXISTS plan_entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_key VARCHAR(48) NOT NULL,
    version INTEGER NOT NULL,
    watermark_required BOOLEAN NOT NULL,
    max_video_quality VARCHAR(24) NOT NULL,
    max_longform_exports_month INTEGER,
    max_short_exports_month INTEGER,
    max_concurrent_expensive_jobs INTEGER NOT NULL,
    feature_flags_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    active_from TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (plan_key, version)
);

CREATE TABLE IF NOT EXISTS user_plan_assignments (
    user_id VARCHAR(128) PRIMARY KEY,
    plan_key VARCHAR(48) NOT NULL,
    entitlement_version INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    period_start TIMESTAMP WITH TIME ZONE NOT NULL,
    period_end TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_windows (
    user_id VARCHAR(128) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    longform_exports INTEGER NOT NULL DEFAULT 0,
    short_exports INTEGER NOT NULL DEFAULT 0,
    expensive_jobs_active INTEGER NOT NULL DEFAULT 0,
    credits_used NUMERIC(19, 6) NOT NULL DEFAULT 0,
    row_version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, period_key)
);

CREATE TABLE IF NOT EXISTS identity_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    character_id BIGINT,
    reference_asset_id BIGINT,
    reference_type VARCHAR(32) NOT NULL,
    consent_basis VARCHAR(128) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_identity_consents_user ON identity_consents (user_id, revoked_at);

CREATE TABLE IF NOT EXISTS identity_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    character_id BIGINT,
    private_template_ref VARCHAR(256) NOT NULL,
    algorithm_version VARCHAR(64) NOT NULL,
    retention_class VARCHAR(48) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS ai_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128),
    project_id BIGINT REFERENCES projects(id),
    job_id BIGINT REFERENCES generation_jobs(id),
    capability VARCHAR(64) NOT NULL,
    provider VARCHAR(64),
    model_key VARCHAR(128),
    prompt_version VARCHAR(64),
    schema_version VARCHAR(64),
    safety_policy_version VARCHAR(64),
    input_fingerprint VARCHAR(128) NOT NULL,
    usage_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    generation_params_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_audit_project_created ON ai_audit_events (project_id, created_at DESC);

CREATE TABLE IF NOT EXISTS data_deletion_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    scope VARCHAR(24) NOT NULL,
    scope_id VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'REQUESTED',
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    error_code VARCHAR(80),
    retention_deadline TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_deletion_requests_user_status ON data_deletion_requests (user_id, status);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id VARCHAR(128) PRIMARY KEY,
    preferred_locale VARCHAR(16) NOT NULL DEFAULT 'vi-VN',
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    default_narration_language VARCHAR(16) NOT NULL DEFAULT 'vi-VN',
    default_metadata_language VARCHAR(16) NOT NULL DEFAULT 'vi-VN',
    row_version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS abuse_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128),
    ip_hash VARCHAR(128),
    session_id VARCHAR(128),
    route_key VARCHAR(128) NOT NULL,
    signal_type VARCHAR(64) NOT NULL,
    action VARCHAR(16) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_abuse_user_created ON abuse_events (user_id, created_at DESC);

-- -----------------------------------------------------------------------------
-- Reusable character identity and project assignments
-- -----------------------------------------------------------------------------

CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    owner_id VARCHAR(128) NOT NULL,
    workspace_id VARCHAR(128),
    canonical_name VARCHAR(160) NOT NULL,
    aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE'
);
CREATE INDEX idx_characters_owner_status ON characters (owner_id, status);

CREATE TABLE character_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    character_id BIGINT NOT NULL REFERENCES characters(id),
    version_number INTEGER NOT NULL,
    bible TEXT NOT NULL,
    visual_prompt TEXT NOT NULL,
    master_asset_id BIGINT,
    reference_asset_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    locked_at TIMESTAMP WITH TIME ZONE,
    locked_by VARCHAR(128),
    CONSTRAINT uk_character_versions_character_version UNIQUE (character_id, version_number)
);
CREATE INDEX idx_character_versions_character_status
    ON character_versions (character_id, status);

CREATE TABLE outfit_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    character_id BIGINT NOT NULL REFERENCES characters(id),
    version_number INTEGER NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    prompt TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    CONSTRAINT uk_outfit_versions_character_version UNIQUE (character_id, version_number),
    CONSTRAINT uk_outfit_versions_id_character UNIQUE (id, character_id)
);

CREATE TABLE character_appearances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    character_id BIGINT NOT NULL REFERENCES characters(id),
    project_id BIGINT REFERENCES projects(id),
    timeline_key VARCHAR(128) NOT NULL,
    age_state TEXT,
    hairstyle TEXT,
    injury TEXT,
    wardrobe_context TEXT,
    appearance_prompt TEXT,
    outfit_version_id BIGINT,
    CONSTRAINT fk_character_appearances_outfit_character
        FOREIGN KEY (outfit_version_id, character_id)
        REFERENCES outfit_versions (id, character_id)
);
CREATE INDEX idx_character_appearances_character_timeline
    ON character_appearances (character_id, timeline_key);

CREATE TABLE project_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    character_id BIGINT NOT NULL REFERENCES characters(id),
    role VARCHAR(64) NOT NULL,
    importance INTEGER NOT NULL DEFAULT 0,
    project_aliases JSONB NOT NULL DEFAULT '[]'::jsonb,
    story_metadata TEXT,
    groups_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    pinned_character_version_id BIGINT REFERENCES character_versions(id),
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uk_project_characters_project_character UNIQUE (project_id, character_id),
    CONSTRAINT ck_project_characters_importance_nonnegative CHECK (importance >= 0)
);
CREATE INDEX idx_project_characters_project_status ON project_characters (project_id, status);
CREATE INDEX idx_project_characters_character ON project_characters (character_id);
