-- Durable v1 domain foundation. Provider/media binaries stay outside PostgreSQL.

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(160) NOT NULL,
    owner_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    source_language VARCHAR(16) NOT NULL,
    narration_language VARCHAR(16) NOT NULL,
    metadata_language VARCHAR(16) NOT NULL,
    image_aspect_ratio VARCHAR(16) NOT NULL,
    image_quality_tier VARCHAR(16) NOT NULL,
    archived_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_projects_owner_status ON projects (owner_id, status);

CREATE TABLE story_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    version_number INTEGER NOT NULL,
    content TEXT NOT NULL,
    source_language VARCHAR(16) NOT NULL,
    status VARCHAR(24) NOT NULL,
    moderation_decision VARCHAR(16) NOT NULL,
    rights_attested BOOLEAN NOT NULL,
    CONSTRAINT uk_story_versions_project_version UNIQUE (project_id, version_number)
);

CREATE TABLE chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    story_version_id BIGINT NOT NULL REFERENCES story_versions(id),
    order_index INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    CONSTRAINT uk_chapters_story_order UNIQUE (story_version_id, order_index)
);

CREATE TABLE scenes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chapter_id BIGINT NOT NULL REFERENCES chapters(id),
    order_index INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    narration TEXT,
    duration_seconds INTEGER,
    CONSTRAINT uk_scenes_chapter_order UNIQUE (chapter_id, order_index)
);

CREATE TABLE visual_beats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    scene_id BIGINT NOT NULL REFERENCES scenes(id),
    order_index INTEGER NOT NULL,
    visual_intent TEXT NOT NULL,
    motion_action VARCHAR(24) NOT NULL,
    aspect_ratio_override VARCHAR(16),
    quality_tier_override VARCHAR(16),
    CONSTRAINT uk_visual_beats_scene_order UNIQUE (scene_id, order_index)
);

CREATE TABLE generation_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    job_id VARCHAR(36) NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    job_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    resource_class VARCHAR(32) NOT NULL,
    progress INTEGER NOT NULL,
    current_step VARCHAR(80),
    error_code VARCHAR(80),
    requested_by_user_id VARCHAR(128) NOT NULL,
    billed_to_user_id VARCHAR(128) NOT NULL
);

CREATE TABLE stage_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    generation_job_id BIGINT NOT NULL REFERENCES generation_jobs(id),
    stage_name VARCHAR(64) NOT NULL,
    attempt_number INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    worker_id VARCHAR(128),
    heartbeat_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_stage_attempts_job_stage_number UNIQUE (generation_job_id, stage_name, attempt_number)
);

CREATE TABLE provider_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    stage_attempt_id BIGINT NOT NULL REFERENCES stage_attempts(id),
    provider_key VARCHAR(64) NOT NULL,
    provider_operation_id VARCHAR(256),
    status VARCHAR(32) NOT NULL,
    reserved_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE operation_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    operation_type VARCHAR(40) NOT NULL,
    estimate_min NUMERIC(19, 6) NOT NULL,
    estimate_max NUMERIC(19, 6) NOT NULL,
    max_authorized_cost NUMERIC(19, 6) NOT NULL,
    confidence VARCHAR(16) NOT NULL
);
