CREATE TABLE chapter_creation_idempotency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id VARCHAR(128) NOT NULL REFERENCES auth_users(id),
    project_id BIGINT NOT NULL REFERENCES projects(id),
    idempotency_key VARCHAR(200) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    chapter_id BIGINT REFERENCES chapters(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_chapter_creation_idempotency UNIQUE (owner_id, project_id, idempotency_key),
    CONSTRAINT ck_chapter_creation_idempotency_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_chapter_creation_idempotency_chapter
    ON chapter_creation_idempotency (chapter_id)
    WHERE chapter_id IS NOT NULL;
