-- Project-scoped read models required by Project Overview tabs.

CREATE TABLE project_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(160) NOT NULL,
    description TEXT,
    visual_prompt TEXT,
    reference_image_url TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT ck_project_locations_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);
CREATE INDEX idx_project_locations_project_updated
    ON project_locations (project_id, updated_at DESC, id DESC);
CREATE INDEX idx_project_locations_active_project
    ON project_locations (project_id, id)
    WHERE status = 'ACTIVE';

CREATE TABLE project_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    asset_type VARCHAR(32) NOT NULL,
    storage_key VARCHAR(512),
    url TEXT,
    mime_type VARCHAR(160),
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_project_assets_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_project_assets_type CHECK (asset_type IN ('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER'))
);
CREATE INDEX idx_project_assets_project_updated
    ON project_assets (project_id, updated_at DESC, id DESC);
CREATE INDEX idx_project_assets_active_project
    ON project_assets (project_id, id)
    WHERE status = 'ACTIVE';

-- Feed indexes for the new account-scoped APIs.
CREATE INDEX idx_generation_jobs_requester_created_id
    ON generation_jobs (requested_by_user_id, created_at DESC, id DESC);
CREATE INDEX idx_notifications_user_created_id
    ON notifications (user_id, created_at DESC, id DESC);
