-- Immutable chapter content lineage and asynchronous translation admission.
CREATE TABLE chapter_content_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id BIGINT NOT NULL REFERENCES chapters(id),
    source_variant_id BIGINT REFERENCES chapter_content_variants(id),
    variant_type VARCHAR(32) NOT NULL,
    language_code VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    source_content_hash VARCHAR(64),
    translation_status VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUIRED',
    translation_provider VARCHAR(64),
    translation_model VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_chapter_content_variants_type
        CHECK (variant_type IN ('ORIGINAL', 'TRANSLATION')),
    CONSTRAINT ck_chapter_content_variants_status
        CHECK (translation_status IN (
            'NOT_REQUIRED', 'PENDING_CONFIRMATION', 'QUEUED', 'TRANSLATING',
            'COMPLETED', 'FAILED', 'CANCELLED', 'STALE'
        )),
    CONSTRAINT ck_chapter_content_variants_hash
        CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_chapter_content_variants_source
        CHECK ((variant_type = 'ORIGINAL' AND source_variant_id IS NULL)
            OR (variant_type = 'TRANSLATION' AND source_variant_id IS NOT NULL AND source_content_hash IS NOT NULL))
);
CREATE UNIQUE INDEX uq_chapter_content_variants_identity
    ON chapter_content_variants (chapter_id, variant_type, language_code, content_hash);
CREATE INDEX idx_chapter_content_variants_chapter_created
    ON chapter_content_variants (chapter_id, created_at DESC, id DESC);

CREATE TABLE language_detections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_variant_id BIGINT NOT NULL REFERENCES chapter_content_variants(id),
    detected_language VARCHAR(32) NOT NULL,
    confidence NUMERIC(5,4) NOT NULL,
    detector VARCHAR(64) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_language_detections_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT ck_language_detections_hash CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT uq_language_detections_variant_hash_detector
        UNIQUE (content_variant_id, content_hash, detector)
);
CREATE INDEX idx_language_detections_variant_created
    ON language_detections (content_variant_id, created_at DESC, id DESC);

ALTER TABLE storyboard_revisions
    ADD COLUMN content_variant_id BIGINT REFERENCES chapter_content_variants(id);

ALTER TABLE generation_jobs
    ADD COLUMN content_variant_id BIGINT REFERENCES chapter_content_variants(id),
    ADD COLUMN source_variant_id BIGINT REFERENCES chapter_content_variants(id),
    ADD COLUMN target_language VARCHAR(32);

ALTER TABLE generation_jobs
    DROP CONSTRAINT ck_generation_jobs_job_type;
ALTER TABLE generation_jobs
    ADD CONSTRAINT ck_generation_jobs_job_type CHECK (job_type IN (
        'STORY_ANALYZE', 'CHAPTER_ANALYZE', 'CHAPTER_TRANSLATE', 'NARRATION_GENERATE', 'IMAGE_GENERATE',
        'CHAPTER_GENERATE', 'CHAPTER_RENDER', 'PROJECT_CONTINUE', 'VISUAL_BEAT_PLAN',
        'SHOT_IMAGE_GENERATE', 'RENDER_PROJECT', 'RENDER_SHORT'
    ));

-- Backfill the current chapter text as the first immutable original variant.
INSERT INTO chapter_content_variants (
    chapter_id, variant_type, language_code, content, content_hash,
    source_content_hash, translation_status, created_at, updated_at
)
SELECT c.id, 'ORIGINAL', COALESCE(NULLIF(p.source_language, ''), 'und'),
       c.source_text, c.source_hash, c.source_hash, 'NOT_REQUIRED', c.created_at, c.updated_at
  FROM chapters c
  JOIN story_versions sv ON sv.id = c.story_version_id
  JOIN projects p ON p.id = sv.project_id
 ON CONFLICT (chapter_id, variant_type, language_code, content_hash) DO NOTHING;

UPDATE storyboard_revisions sr
   SET content_variant_id = v.id
  FROM chapter_content_variants v
 WHERE sr.content_variant_id IS NULL
   AND v.chapter_id = sr.chapter_id
   AND v.variant_type = 'ORIGINAL'
   AND v.content_hash = sr.source_hash;

UPDATE generation_jobs gj
   SET content_variant_id = v.id
  FROM chapter_content_variants v
 WHERE gj.content_variant_id IS NULL
   AND gj.chapter_id = v.chapter_id
   AND v.variant_type = 'ORIGINAL'
   AND v.content_hash = gj.source_hash;
