-- NarrativeX v1.7 control-plane foundation.
-- User-facing policy decisions are durable PostgreSQL state; Redis remains acceleration only.

ALTER TABLE story_versions
    ADD COLUMN IF NOT EXISTS rights_policy_version VARCHAR(64) NOT NULL DEFAULT 'rights-v1.7',
    ADD COLUMN IF NOT EXISTS rights_basis VARCHAR(64) NOT NULL DEFAULT 'USER_ATTESTED_RIGHTS_OR_LICENSE',
    ADD COLUMN IF NOT EXISTS rights_attested_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS rights_attested_by VARCHAR(128);

ALTER TABLE chapters
    ADD COLUMN IF NOT EXISTS source_text TEXT,
    ADD COLUMN IF NOT EXISTS status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN IF NOT EXISTS estimated_duration_ms BIGINT,
    ADD COLUMN IF NOT EXISTS generation_progress INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS source_story_version_id BIGINT REFERENCES story_versions(id),
    ADD COLUMN IF NOT EXISTS inherited_snapshot_hash VARCHAR(128);

CREATE TABLE IF NOT EXISTS content_rights_attestations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_version_id BIGINT NOT NULL REFERENCES story_versions(id),
    user_id VARCHAR(128) NOT NULL,
    rights_basis VARCHAR(64) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_rights_attestations_story_active
    ON content_rights_attestations (story_version_id, revoked_at);

CREATE TABLE IF NOT EXISTS moderation_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128),
    project_id BIGINT REFERENCES projects(id),
    entity_type VARCHAR(48) NOT NULL,
    entity_id VARCHAR(128) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    result VARCHAR(16) NOT NULL,
    categories_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    provider_signal_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    policy_version VARCHAR(64) NOT NULL,
    reviewer_id VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_moderation_entity ON moderation_decisions (entity_type, entity_id, created_at DESC);

CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id VARCHAR(128) PRIMARY KEY,
    render_complete_email BOOLEAN NOT NULL DEFAULT FALSE,
    render_failed_email BOOLEAN NOT NULL DEFAULT FALSE,
    short_complete_email BOOLEAN NOT NULL DEFAULT FALSE,
    web_push_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    row_version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    project_id BIGINT REFERENCES projects(id),
    event_key VARCHAR(160) NOT NULL UNIQUE,
    type VARCHAR(48) NOT NULL,
    channel_state_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    title_key VARCHAR(128) NOT NULL,
    message_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON notifications (user_id, read_at, created_at DESC);

CREATE TABLE IF NOT EXISTS outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(128) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    event_key VARCHAR(160) NOT NULL UNIQUE,
    payload_json JSONB NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON outbox_events (status, available_at);

CREATE TABLE IF NOT EXISTS plan_entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_key VARCHAR(48) NOT NULL,
    version INTEGER NOT NULL,
    watermark_required BOOLEAN NOT NULL,
    max_video_quality VARCHAR(24) NOT NULL,
    max_longform_exports_month INTEGER,
    max_short_exports_month INTEGER,
    max_concurrent_expensive_jobs INTEGER NOT NULL,
    feature_flags_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    active_from TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (plan_key, version)
);

CREATE TABLE IF NOT EXISTS user_plan_assignments (
    user_id VARCHAR(128) PRIMARY KEY,
    plan_key VARCHAR(48) NOT NULL,
    entitlement_version INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    period_start TIMESTAMP WITH TIME ZONE NOT NULL,
    period_end TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_windows (
    user_id VARCHAR(128) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    longform_exports INTEGER NOT NULL DEFAULT 0,
    short_exports INTEGER NOT NULL DEFAULT 0,
    expensive_jobs_active INTEGER NOT NULL DEFAULT 0,
    credits_used NUMERIC(19, 6) NOT NULL DEFAULT 0,
    row_version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, period_key)
);

CREATE TABLE IF NOT EXISTS identity_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    character_id BIGINT,
    reference_asset_id BIGINT,
    reference_type VARCHAR(32) NOT NULL,
    consent_basis VARCHAR(128) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_identity_consents_user ON identity_consents (user_id, revoked_at);

CREATE TABLE IF NOT EXISTS identity_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    character_id BIGINT,
    private_template_ref VARCHAR(256) NOT NULL,
    algorithm_version VARCHAR(64) NOT NULL,
    retention_class VARCHAR(48) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS ai_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128),
    project_id BIGINT REFERENCES projects(id),
    job_id BIGINT REFERENCES generation_jobs(id),
    capability VARCHAR(64) NOT NULL,
    provider VARCHAR(64),
    model_key VARCHAR(128),
    prompt_version VARCHAR(64),
    schema_version VARCHAR(64),
    safety_policy_version VARCHAR(64),
    input_fingerprint VARCHAR(128) NOT NULL,
    usage_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    generation_params_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_audit_project_created ON ai_audit_events (project_id, created_at DESC);

CREATE TABLE IF NOT EXISTS data_deletion_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    scope VARCHAR(24) NOT NULL,
    scope_id VARCHAR(128) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'REQUESTED',
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    error_code VARCHAR(80),
    retention_deadline TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_deletion_requests_user_status ON data_deletion_requests (user_id, status);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id VARCHAR(128) PRIMARY KEY,
    preferred_locale VARCHAR(16) NOT NULL DEFAULT 'vi-VN',
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
    default_narration_language VARCHAR(16) NOT NULL DEFAULT 'vi-VN',
    default_metadata_language VARCHAR(16) NOT NULL DEFAULT 'vi-VN',
    row_version BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS abuse_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128),
    ip_hash VARCHAR(128),
    session_id VARCHAR(128),
    route_key VARCHAR(128) NOT NULL,
    signal_type VARCHAR(64) NOT NULL,
    action VARCHAR(16) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_abuse_user_created ON abuse_events (user_id, created_at DESC);
