CREATE TABLE style_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    category VARCHAR(32) NOT NULL,
    description TEXT NOT NULL,
    thumbnail_url TEXT,
    prompt_suffix TEXT,
    negative_prompt TEXT,
    tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by VARCHAR(128) REFERENCES auth_users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT ck_style_presets_category CHECK (category IN ('VISUAL_STYLE', 'IMAGE', 'MOTION', 'OUTFIT', 'RENDER')),
    CONSTRAINT ck_style_presets_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_style_presets_tags_array CHECK (jsonb_typeof(tags_json) = 'array'),
    CONSTRAINT ck_style_presets_config_object CHECK (jsonb_typeof(config_json) = 'object')
);
CREATE INDEX idx_style_presets_active_category_name
    ON style_presets (category, LOWER(name), id)
    WHERE status = 'ACTIVE';

CREATE TABLE voice_catalog (
    id VARCHAR(160) PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    name VARCHAR(160) NOT NULL,
    language VARCHAR(32) NOT NULL,
    gender VARCHAR(24),
    sample_url TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_voice_catalog_metadata_object CHECK (jsonb_typeof(metadata_json) = 'object')
);
CREATE INDEX idx_voice_catalog_enabled_language_name
    ON voice_catalog (language, LOWER(name), id)
    WHERE enabled = TRUE;

INSERT INTO style_presets
    (id, name, category, description, thumbnail_url, prompt_suffix, negative_prompt, tags_json, config_json)
VALUES
    (1, 'Cinematic Warmth', 'VISUAL_STYLE', 'Warm cinematic lighting with grounded texture.',
     'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
     'cinematic composition, warm practical light, subtle film grain',
     'blurry, distorted anatomy, text, watermark',
     '["cinematic", "warm", "story"]'::jsonb,
     '{"defaultAspectRatio":"16:9","defaultQuality":"Standard","lighting":"warm practical","atmosphere":"intimate"}'::jsonb),
    (2, 'Storybook Watercolor', 'IMAGE', 'Soft illustrated treatment for intimate story moments.',
     'https://images.unsplash.com/photo-1549490349-8643362247b5',
     'storybook watercolor illustration, soft edges, expressive silhouettes',
     'photorealistic, harsh contrast, text, watermark',
     '["illustration", "watercolor", "soft"]'::jsonb,
     '{"defaultAspectRatio":"16:9","defaultQuality":"Standard","lighting":"diffused","atmosphere":"dreamy"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

SELECT setval('style_presets_id_seq', COALESCE((SELECT MAX(id) FROM style_presets), 1), true);

INSERT INTO voice_catalog (id, provider, name, language, gender, sample_url, metadata_json)
VALUES
    ('narrativex-en-us-female-1', 'NARRATIVEX', 'Clara', 'en-US', 'FEMALE', NULL, '{"style":"warm"}'::jsonb),
    ('narrativex-vi-vn-female-1', 'NARRATIVEX', 'Mai', 'vi-VN', 'FEMALE', NULL, '{"style":"natural"}'::jsonb),
    ('narrativex-vi-vn-male-1', 'NARRATIVEX', 'An', 'vi-VN', 'MALE', NULL, '{"style":"calm"}'::jsonb)
ON CONFLICT (id) DO NOTHING;
