-- Durable quota reservation lifecycle with actual provider-cost reconciliation.
-- RESERVED rows own concurrent capacity and authorized credit. Terminal settlement uses durable
-- provider billing evidence rather than the authorization estimate.

ALTER TABLE provider_operations
    ADD COLUMN actual_cost NUMERIC(19, 9),
    ADD COLUMN billing_currency VARCHAR(3),
    ADD COLUMN usage_json JSONB,
    ADD COLUMN pricing_snapshot_json JSONB;

ALTER TABLE provider_operations
    ADD CONSTRAINT ck_provider_operations_actual_cost_nonnegative
        CHECK (actual_cost IS NULL OR actual_cost >= 0),
    ADD CONSTRAINT ck_provider_operations_billing_complete
        CHECK (
            (actual_cost IS NULL AND billing_currency IS NULL AND usage_json IS NULL
                AND pricing_snapshot_json IS NULL)
            OR (actual_cost IS NOT NULL AND billing_currency IS NOT NULL
                AND usage_json IS NOT NULL AND pricing_snapshot_json IS NOT NULL)
        );

CREATE TABLE quota_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMP WITH TIME ZONE,
    user_id VARCHAR(128) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    generation_job_id BIGINT UNIQUE REFERENCES generation_jobs(id),
    estimated_cost NUMERIC(19, 6) NOT NULL,
    actual_cost NUMERIC(19, 9),
    billing_currency VARCHAR(3),
    status VARCHAR(16) NOT NULL,
    CONSTRAINT ck_quota_reservations_cost_nonnegative CHECK (estimated_cost >= 0),
    CONSTRAINT ck_quota_reservations_actual_cost_nonnegative
        CHECK (actual_cost IS NULL OR actual_cost >= 0),
    CONSTRAINT ck_quota_reservations_status
        CHECK (status IN ('RESERVED', 'CONSUMED', 'RELEASED')),
    CONSTRAINT ck_quota_reservations_finalized
        CHECK (
            (status = 'RESERVED' AND finalized_at IS NULL)
            OR (status IN ('CONSUMED', 'RELEASED') AND finalized_at IS NOT NULL)
        )
);

CREATE INDEX idx_quota_reservations_user_status
    ON quota_reservations (user_id, status);
CREATE INDEX idx_quota_reservations_user_period_status
    ON quota_reservations (user_id, period_key, status);
CREATE INDEX idx_quota_reservations_active_user
    ON quota_reservations (user_id, id)
    WHERE status = 'RESERVED';

-- Historical terminal jobs predate durable provider usage capture. Preserve the amount charged by
-- the old implementation as the best available actual-cost value; new jobs never use this fallback.
INSERT INTO quota_reservations
    (user_id, period_key, generation_job_id, estimated_cost, actual_cost, billing_currency,
     status, finalized_at, created_at, updated_at)
SELECT billed_to_user_id,
       to_char(generation_job_created_at AT TIME ZONE 'UTC', 'YYYY-MM'),
       generation_job_id,
       max_authorized_cost,
       CASE WHEN generation_job_status = 'COMPLETED' THEN max_authorized_cost ELSE 0 END,
       CASE WHEN generation_job_status IN ('COMPLETED', 'FAILED', 'CANCELED') THEN 'USD' ELSE NULL END,
       CASE
           WHEN generation_job_status = 'COMPLETED' THEN 'CONSUMED'
           WHEN generation_job_status IN ('FAILED', 'CANCELED') THEN 'RELEASED'
           ELSE 'RESERVED'
       END,
       CASE
           WHEN generation_job_status IN ('COMPLETED', 'FAILED', 'CANCELED')
               THEN CURRENT_TIMESTAMP
           ELSE NULL
       END,
       generation_job_created_at,
       CURRENT_TIMESTAMP
  FROM (
      SELECT DISTINCT ON (gj.id)
             gj.id AS generation_job_id,
             gj.billed_to_user_id,
             gj.status AS generation_job_status,
             gj.created_at AS generation_job_created_at,
             op.max_authorized_cost,
             op.id AS operation_plan_id
        FROM generation_jobs gj
        JOIN operation_plans op ON op.generation_job_id = gj.id
       ORDER BY gj.id, op.id DESC
  ) admitted_jobs
ON CONFLICT (generation_job_id) DO NOTHING;

-- The previous implementation charged authorized cost immediately at reserve time. Move
-- non-consumed reservations back out of credits_used so only CONSUMED work remains charged.
UPDATE usage_windows uw
   SET credits_used = GREATEST(0::numeric, uw.credits_used - refundable.estimated_cost),
       expensive_jobs_active = 0,
       row_version = uw.row_version + 1
  FROM (
      SELECT user_id, period_key, SUM(estimated_cost) AS estimated_cost
        FROM quota_reservations
       WHERE status IN ('RESERVED', 'RELEASED')
       GROUP BY user_id, period_key
  ) refundable
 WHERE uw.user_id = refundable.user_id
   AND uw.period_key = refundable.period_key;

UPDATE usage_windows
   SET expensive_jobs_active = 0,
       row_version = row_version + 1
 WHERE expensive_jobs_active <> 0;

COMMENT ON COLUMN usage_windows.expensive_jobs_active IS
    'Deprecated projection. Active expensive jobs are derived from quota_reservations status RESERVED.';
COMMENT ON COLUMN quota_reservations.estimated_cost IS
    'Admission authorization amount; RESERVED capacity uses this value.';
COMMENT ON COLUMN quota_reservations.actual_cost IS
    'Terminal provider cost reconciled from durable provider usage; never used for admission.';

-- Keep quota settlement in the exact transaction that makes a GenerationJob terminal. Billing
-- evidence is persisted before this transition. Repeating the terminal update cannot double-charge
-- because only RESERVED reservations are eligible for settlement.
CREATE OR REPLACE FUNCTION finalize_quota_reservation_on_job_terminal()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    reconciled_cost NUMERIC(19, 9);
    reconciled_currency VARCHAR(3);
    billed_operation_count INTEGER;
BEGIN
    SELECT COALESCE(SUM(po.actual_cost), 0),
           CASE
               WHEN COUNT(DISTINCT po.billing_currency)
                    FILTER (WHERE po.actual_cost IS NOT NULL) = 1
                   THEN MAX(po.billing_currency) FILTER (WHERE po.actual_cost IS NOT NULL)
               ELSE NULL
           END,
           COUNT(*) FILTER (WHERE po.actual_cost IS NOT NULL)
      INTO reconciled_cost, reconciled_currency, billed_operation_count
      FROM provider_operations po
      JOIN stage_attempts sa ON sa.id = po.stage_attempt_id
     WHERE sa.generation_job_id = NEW.id;

    IF NEW.status = 'COMPLETED' AND OLD.status IS DISTINCT FROM 'COMPLETED' THEN
        IF billed_operation_count = 0 OR reconciled_currency IS NULL THEN
            RAISE EXCEPTION
                'Cannot complete generation job % without reconciled provider billing', NEW.id;
        END IF;

        WITH consumed AS (
            UPDATE quota_reservations
               SET status = 'CONSUMED',
                   actual_cost = reconciled_cost,
                   billing_currency = reconciled_currency,
                   finalized_at = CURRENT_TIMESTAMP,
                   updated_at = CURRENT_TIMESTAMP,
                   row_version = row_version + 1
             WHERE generation_job_id = NEW.id
               AND status = 'RESERVED'
             RETURNING user_id, period_key, actual_cost
        )
        UPDATE usage_windows uw
           SET credits_used = uw.credits_used + consumed.actual_cost,
               row_version = uw.row_version + 1
          FROM consumed
         WHERE uw.user_id = consumed.user_id
           AND uw.period_key = consumed.period_key;
    ELSIF NEW.status IN ('FAILED', 'CANCELED')
          AND OLD.status IS DISTINCT FROM NEW.status THEN
        IF billed_operation_count > 0
           AND reconciled_currency IS NOT NULL
           AND reconciled_cost > 0 THEN
            WITH consumed AS (
                UPDATE quota_reservations
                   SET status = 'CONSUMED',
                       actual_cost = reconciled_cost,
                       billing_currency = reconciled_currency,
                       finalized_at = CURRENT_TIMESTAMP,
                       updated_at = CURRENT_TIMESTAMP,
                       row_version = row_version + 1
                 WHERE generation_job_id = NEW.id
                   AND status = 'RESERVED'
                 RETURNING user_id, period_key, actual_cost
            )
            UPDATE usage_windows uw
               SET credits_used = uw.credits_used + consumed.actual_cost,
                   row_version = uw.row_version + 1
              FROM consumed
             WHERE uw.user_id = consumed.user_id
               AND uw.period_key = consumed.period_key;
        ELSE
            UPDATE quota_reservations
               SET status = 'RELEASED',
                   actual_cost = 0,
                   billing_currency = COALESCE(reconciled_currency, 'USD'),
                   finalized_at = CURRENT_TIMESTAMP,
                   updated_at = CURRENT_TIMESTAMP,
                   row_version = row_version + 1
             WHERE generation_job_id = NEW.id
               AND status = 'RESERVED';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_generation_jobs_finalize_quota
AFTER UPDATE OF status ON generation_jobs
FOR EACH ROW
WHEN (NEW.status IN ('COMPLETED', 'FAILED', 'CANCELED'))
EXECUTE FUNCTION finalize_quota_reservation_on_job_terminal();
