-- NarrativeX pre-release baseline: catalog/read models, upload lifecycle, media generation, and immutable project-render snapshots.

-- -----------------------------------------------------------------------------
-- Catalog read models and upload lifecycle
-- -----------------------------------------------------------------------------

CREATE TABLE style_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    category VARCHAR(32) NOT NULL,
    description TEXT NOT NULL,
    thumbnail_url TEXT,
    prompt_suffix TEXT,
    negative_prompt TEXT,
    tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_by VARCHAR(128) REFERENCES auth_users(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT ck_style_presets_category CHECK (category IN ('VISUAL_STYLE', 'IMAGE', 'MOTION', 'OUTFIT', 'RENDER')),
    CONSTRAINT ck_style_presets_status CHECK (status IN ('ACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_style_presets_tags_array CHECK (jsonb_typeof(tags_json) = 'array'),
    CONSTRAINT ck_style_presets_config_object CHECK (jsonb_typeof(config_json) = 'object')
);

CREATE TABLE voice_catalog (
    id VARCHAR(160) PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    name VARCHAR(160) NOT NULL,
    language VARCHAR(32) NOT NULL,
    gender VARCHAR(24),
    sample_url TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_voice_catalog_metadata_object CHECK (jsonb_typeof(metadata_json) = 'object')
);

CREATE TABLE media_upload_sessions (
    id UUID PRIMARY KEY,
    account_id VARCHAR(128) NOT NULL,
    asset_type VARCHAR(16) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(160) NOT NULL,
    expected_size BIGINT NOT NULL,
    expected_sha256 VARCHAR(64) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    idempotency_key VARCHAR(255),
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING_UPLOAD',
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    media_asset_id UUID REFERENCES media_assets(id),
    CONSTRAINT ck_media_upload_sessions_type CHECK (asset_type IN ('AUDIO', 'IMAGE', 'VIDEO')),
    CONSTRAINT ck_media_upload_sessions_size CHECK (expected_size > 0),
    CONSTRAINT ck_media_upload_sessions_sha256 CHECK (expected_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_media_upload_sessions_status CHECK (status IN ('PENDING_UPLOAD', 'VALIDATING', 'READY', 'REJECTED')),
    CONSTRAINT uk_media_upload_sessions_storage_key UNIQUE (storage_key),
    CONSTRAINT uk_media_upload_sessions_idempotency UNIQUE (account_id, idempotency_key)
);

CREATE TABLE media_storage_cleanup_tasks (
    id UUID PRIMARY KEY,
    storage_key VARCHAR(512) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_error VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_media_storage_cleanup_status CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED')),
    CONSTRAINT ck_media_storage_cleanup_attempts CHECK (attempt_count >= 0)
);

-- -----------------------------------------------------------------------------
-- Media generation execution and lineage
-- -----------------------------------------------------------------------------

CREATE TABLE media_generation_items (
    id UUID PRIMARY KEY,
    generation_job_id UUID NOT NULL REFERENCES generation_jobs(id) ON DELETE CASCADE,
    media_plan_id UUID NOT NULL REFERENCES media_plans(id),
    visual_beat_id UUID NOT NULL REFERENCES visual_beats(id),
    item_key VARCHAR(160) NOT NULL,
    attempt_number INTEGER NOT NULL,
    execution_status VARCHAR(24) NOT NULL,
    provider_operation_id UUID REFERENCES provider_operations(id),
    media_asset_id UUID REFERENCES media_assets(id),
    request_fingerprint VARCHAR(128) NOT NULL,
    error_code VARCHAR(80),
    error_detail_ref VARCHAR(160),
    review_status VARCHAR(24) NOT NULL DEFAULT 'NOT_READY',
    reviewed_by_user_id VARCHAR(128),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    row_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_media_generation_items_attempt UNIQUE (generation_job_id, item_key, attempt_number),
    CONSTRAINT ck_media_generation_items_attempt CHECK (attempt_number > 0),
    CONSTRAINT ck_media_generation_items_execution_status CHECK (execution_status IN ('QUEUED', 'RUNNING', 'VALIDATING', 'READY', 'FAILED', 'UNKNOWN')),
    CONSTRAINT ck_media_generation_items_review_status CHECK (review_status IN ('NOT_READY', 'NEEDS_REVIEW', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_media_generation_items_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64,128}$'),
    CONSTRAINT ck_media_generation_items_review_fields CHECK (
        (review_status IN ('NOT_READY', 'NEEDS_REVIEW') AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL)
        OR
        (review_status IN ('APPROVED', 'REJECTED') AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL)
    )
);

CREATE TABLE media_asset_lineage (
    id UUID PRIMARY KEY,
    media_asset_id UUID NOT NULL REFERENCES media_assets(id),
    account_id VARCHAR(128) NOT NULL,
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    chapter_id UUID NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    visual_beat_id UUID NOT NULL REFERENCES visual_beats(id),
    generation_job_id UUID NOT NULL REFERENCES generation_jobs(id),
    media_plan_id UUID NOT NULL REFERENCES media_plans(id),
    generation_item_id UUID NOT NULL REFERENCES media_generation_items(id),
    source_asset_id UUID REFERENCES media_assets(id),
    relation_type VARCHAR(32) NOT NULL,
    request_fingerprint VARCHAR(128) NOT NULL,
    result_fingerprint VARCHAR(128),
    prompt_snapshot TEXT,
    provider_snapshot_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_media_asset_lineage_logical UNIQUE (generation_item_id, relation_type),
    CONSTRAINT ck_media_asset_lineage_relation CHECK (relation_type IN ('GENERATED_KEYFRAME', 'DERIVED_KEYFRAME', 'RENDER_INPUT')),
    CONSTRAINT ck_media_asset_lineage_request_fingerprint CHECK (request_fingerprint ~ '^[0-9a-f]{64,128}$'),
    CONSTRAINT ck_media_asset_lineage_result_fingerprint CHECK (result_fingerprint IS NULL OR result_fingerprint ~ '^[0-9a-f]{64,128}$'),
    CONSTRAINT ck_media_asset_lineage_provider_snapshot_object CHECK (provider_snapshot_json IS NULL OR jsonb_typeof(provider_snapshot_json) = 'object'),
    CONSTRAINT ck_media_asset_lineage_prompt_snapshot_size CHECK (prompt_snapshot IS NULL OR length(prompt_snapshot) <= 16000)
);

CREATE TABLE chapter_media_heads (
    chapter_id UUID PRIMARY KEY REFERENCES chapters(id) ON DELETE CASCADE,
    generation_job_id UUID NOT NULL UNIQUE REFERENCES generation_jobs(id) ON DELETE CASCADE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------------------------------
-- Project render snapshots and Desktop execution assignment
-- -----------------------------------------------------------------------------

CREATE TABLE project_render_input_snapshots (
    generation_job_id UUID PRIMARY KEY REFERENCES generation_jobs(id) ON DELETE CASCADE,
    project_id UUID NOT NULL REFERENCES projects(id),
    story_version_id UUID NOT NULL REFERENCES story_versions(id),
    resolution VARCHAR(16) NOT NULL,
    render_format VARCHAR(16) NOT NULL,
    aspect_ratio VARCHAR(16) NOT NULL,
    total_duration_ms BIGINT NOT NULL CHECK (total_duration_ms > 0),
    chapter_count INTEGER NOT NULL CHECK (chapter_count > 0),
    beat_count INTEGER NOT NULL CHECK (beat_count > 0),
    assigned_local_device_id UUID NOT NULL REFERENCES local_devices(id),
    render_profile_json JSONB NOT NULL DEFAULT '{
      "schemaVersion": 2,
      "rendererVersion": "project-image-motion-v3-composition",
      "compositionPolicyVersion": 1,
      "fps": 30,
      "video": {
        "x264Preset": "medium",
        "crf": 18,
        "nvencPreset": "p6",
        "nvencCq": 19,
        "pixelFormat": "yuv420p"
      },
      "color": {"mode": "SDR_BT709_LIMITED"},
      "subtitles": {"mode": "none"}
    }'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_project_render_input_resolution CHECK (resolution IN ('720p', '1080p', '1440p')),
    CONSTRAINT ck_project_render_input_format CHECK (render_format = 'mp4'),
    CONSTRAINT ck_project_render_profile_object CHECK (jsonb_typeof(render_profile_json) = 'object'),
    CONSTRAINT ck_project_render_profile_version CHECK ((render_profile_json ->> 'schemaVersion')::integer = 2)
);

CREATE TABLE project_render_input_chapters (
    generation_job_id UUID NOT NULL REFERENCES project_render_input_snapshots(generation_job_id) ON DELETE CASCADE,
    chapter_id UUID NOT NULL REFERENCES chapters(id),
    chapter_order_index INTEGER NOT NULL,
    chapter_row_version BIGINT NOT NULL,
    source_hash VARCHAR(64) NOT NULL,
    media_plan_id UUID REFERENCES media_plans(id),
    media_plan_revision INTEGER CHECK (media_plan_revision IS NULL OR media_plan_revision > 0),
    global_start_ms BIGINT NOT NULL CHECK (global_start_ms >= 0),
    global_end_ms BIGINT NOT NULL,
    audio_storage_key TEXT NOT NULL,
    audio_size_bytes BIGINT NOT NULL CHECK (audio_size_bytes > 0),
    audio_checksum VARCHAR(128) NOT NULL,
    audio_duration_ms BIGINT NOT NULL CHECK (audio_duration_ms > 0),
    narration_request_id UUID,
    narration_asset_id UUID,
    narration_alignment_id UUID,
    subtitle_text TEXT NOT NULL DEFAULT '',
    subtitle_spans_json JSONB,
    PRIMARY KEY (generation_job_id, chapter_id),
    CONSTRAINT ck_project_render_chapter_range CHECK (global_end_ms > global_start_ms),
    CONSTRAINT ck_project_render_subtitle_spans_array
        CHECK (subtitle_spans_json IS NULL OR jsonb_typeof(subtitle_spans_json) = 'array')
);

COMMENT ON COLUMN project_render_input_chapters.subtitle_text IS
    'Immutable narration source text captured when the project render job is admitted.';
COMMENT ON COLUMN project_render_input_chapters.subtitle_spans_json IS
    'Immutable narration alignment spans [{index,textStart,textEnd,audioStartMs,audioEndMs}] used for subtitle timing.';

CREATE TABLE project_render_input_beats (
    generation_job_id UUID NOT NULL REFERENCES project_render_input_snapshots(generation_job_id) ON DELETE CASCADE,
    chapter_id UUID NOT NULL REFERENCES chapters(id),
    scene_index INTEGER NOT NULL,
    beat_index INTEGER NOT NULL,
    visual_beat_id UUID NOT NULL,
    media_asset_id UUID NOT NULL REFERENCES media_assets(id),
    global_start_ms BIGINT NOT NULL CHECK (global_start_ms >= 0),
    global_end_ms BIGINT NOT NULL,
    duration_ms BIGINT NOT NULL CHECK (duration_ms > 0),
    camera_movement VARCHAR(32) NOT NULL DEFAULT 'NONE',
    storage_key TEXT,
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    checksum VARCHAR(128) NOT NULL,
    media_type VARCHAR(16) NOT NULL DEFAULT 'IMAGE',
    storage_mode VARCHAR(24) NOT NULL DEFAULT 'PROJECT_LOCAL',
    source_duration_ms BIGINT,
    fit_mode VARCHAR(24) NOT NULL DEFAULT 'TRIM',
    trim_start_ms BIGINT NOT NULL DEFAULT 0,
    media_selection_active BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (generation_job_id, visual_beat_id),
    CONSTRAINT ck_project_render_beat_range CHECK (global_end_ms > global_start_ms),
    CONSTRAINT ck_project_render_input_beat_media_type CHECK (media_type IN ('IMAGE', 'VIDEO')),
    CONSTRAINT ck_project_render_input_beat_storage_mode CHECK (storage_mode IN ('PROJECT_LOCAL', 'LOCAL_ONLY')),
    CONSTRAINT ck_project_render_input_beat_source_duration CHECK (source_duration_ms IS NULL OR source_duration_ms > 0),
    CONSTRAINT ck_project_render_input_beat_fit_mode CHECK (fit_mode IN ('TRIM', 'LOOP', 'FREEZE_END', 'SPEED_ADJUST')),
    CONSTRAINT ck_project_render_input_beat_trim_start CHECK (trim_start_ms >= 0)
);
