-- Version storyboard materialization so approved output is never overwritten by re-analysis.
CREATE TABLE storyboard_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    chapter_id BIGINT NOT NULL REFERENCES chapters(id),
    revision_number INTEGER NOT NULL,
    source_hash VARCHAR(64) NOT NULL,
    source_row_version BIGINT NOT NULL,
    based_on_revision_id BIGINT REFERENCES storyboard_revisions(id),
    status VARCHAR(24) NOT NULL DEFAULT 'DRAFT',
    CONSTRAINT uk_storyboard_revisions_chapter_number UNIQUE (chapter_id, revision_number),
    CONSTRAINT ck_storyboard_revisions_status CHECK (status IN ('DRAFT', 'FAILED')),
    CONSTRAINT ck_storyboard_revisions_source_hash CHECK (source_hash ~ '^[0-9a-f]{64}$')
);

ALTER TABLE chapters ADD COLUMN current_storyboard_revision_id BIGINT REFERENCES storyboard_revisions(id);
ALTER TABLE scenes ADD COLUMN storyboard_revision_id BIGINT REFERENCES storyboard_revisions(id);
ALTER TABLE generation_jobs ADD COLUMN storyboard_revision_id BIGINT REFERENCES storyboard_revisions(id);

-- Backfill existing storyboards as revision 1. Existing review/approval state remains on Scene/VisualBeat.
INSERT INTO storyboard_revisions (chapter_id, revision_number, source_hash, source_row_version, status)
SELECT c.id, 1, c.source_hash, c.row_version, 'DRAFT'
  FROM chapters c
 WHERE EXISTS (SELECT 1 FROM scenes s WHERE s.chapter_id = c.id);

UPDATE scenes s
   SET storyboard_revision_id = sr.id
  FROM storyboard_revisions sr
 WHERE sr.chapter_id = s.chapter_id
   AND sr.revision_number = 1;

UPDATE chapters c
   SET current_storyboard_revision_id = sr.id
  FROM storyboard_revisions sr
 WHERE sr.chapter_id = c.id
   AND sr.revision_number = 1;

ALTER TABLE scenes ALTER COLUMN storyboard_revision_id SET NOT NULL;

ALTER TABLE scenes DROP CONSTRAINT uk_scenes_chapter_order;
ALTER TABLE scenes ADD CONSTRAINT uk_scenes_revision_order UNIQUE (storyboard_revision_id, order_index);

CREATE INDEX idx_storyboard_revisions_chapter_created
    ON storyboard_revisions (chapter_id, revision_number DESC);
CREATE INDEX idx_scenes_revision_status
    ON scenes (storyboard_revision_id, status);
