-- Immutable render inputs and durable final render artifacts.

CREATE TABLE render_manifests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    chapter_id BIGINT NOT NULL REFERENCES chapters(id) ON DELETE CASCADE,
    media_plan_id UUID REFERENCES media_plans(id),
    chapter_row_version BIGINT NOT NULL CHECK (chapter_row_version >= 0),
    source_hash VARCHAR(64) NOT NULL,
    render_fingerprint VARCHAR(64) NOT NULL,
    manifest_json JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_render_manifests_fingerprint UNIQUE (render_fingerprint),
    CONSTRAINT ck_render_manifests_source_hash
        CHECK (source_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_render_manifests_fingerprint
        CHECK (render_fingerprint ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_render_manifests_chapter_created
    ON render_manifests (chapter_id, created_at DESC, id DESC);

CREATE TABLE final_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    chapter_id BIGINT REFERENCES chapters(id) ON DELETE CASCADE,
    generation_job_id BIGINT REFERENCES generation_jobs(id) ON DELETE SET NULL,
    render_manifest_id BIGINT REFERENCES render_manifests(id) ON DELETE SET NULL,
    artifact_type VARCHAR(32) NOT NULL,
    render_fingerprint VARCHAR(64) NOT NULL,
    storage_key VARCHAR(1024) NOT NULL,
    mime_type VARCHAR(160) NOT NULL,
    size_bytes BIGINT,
    checksum_sha256 VARCHAR(64),
    duration_ms BIGINT,
    width INTEGER,
    height INTEGER,
    fps NUMERIC(8,3),
    status VARCHAR(24) NOT NULL DEFAULT 'READY',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_final_artifacts_type
        CHECK (artifact_type IN ('CHAPTER_VIDEO', 'PROJECT_VIDEO', 'SHORT_VIDEO')),
    CONSTRAINT ck_final_artifacts_status
        CHECK (status IN ('PENDING', 'READY', 'FAILED', 'ARCHIVED')),
    CONSTRAINT ck_final_artifacts_fingerprint
        CHECK (render_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_final_artifacts_checksum
        CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_final_artifacts_size_nonnegative
        CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT ck_final_artifacts_duration_nonnegative
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT ck_final_artifacts_dimensions_positive
        CHECK ((width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)),
    CONSTRAINT ck_final_artifacts_fps_positive
        CHECK (fps IS NULL OR fps > 0)
);

CREATE UNIQUE INDEX uq_final_artifacts_chapter_render_fingerprint
    ON final_artifacts (chapter_id, render_fingerprint)
    WHERE chapter_id IS NOT NULL AND status <> 'ARCHIVED';

CREATE INDEX idx_final_artifacts_project_created
    ON final_artifacts (project_id, created_at DESC, id DESC);

CREATE INDEX idx_final_artifacts_chapter_created
    ON final_artifacts (chapter_id, created_at DESC, id DESC)
    WHERE chapter_id IS NOT NULL;
