-- Durable quota reservation lifecycle for expensive generation work.
-- RESERVED rows own concurrent capacity and authorized credit. COMPLETED jobs consume the
-- reservation; failed/canceled jobs release it. UNKNOWN/non-terminal jobs keep it reserved.

CREATE TABLE quota_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMP WITH TIME ZONE,
    user_id VARCHAR(128) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    generation_job_id BIGINT UNIQUE REFERENCES generation_jobs(id),
    estimated_cost NUMERIC(19, 6) NOT NULL,
    status VARCHAR(16) NOT NULL,
    CONSTRAINT ck_quota_reservations_cost_nonnegative CHECK (estimated_cost >= 0),
    CONSTRAINT ck_quota_reservations_status
        CHECK (status IN ('RESERVED', 'CONSUMED', 'RELEASED')),
    CONSTRAINT ck_quota_reservations_finalized
        CHECK (
            (status = 'RESERVED' AND finalized_at IS NULL)
            OR (status IN ('CONSUMED', 'RELEASED') AND finalized_at IS NOT NULL)
        )
);

CREATE INDEX idx_quota_reservations_user_status
    ON quota_reservations (user_id, status);
CREATE INDEX idx_quota_reservations_user_period_status
    ON quota_reservations (user_id, period_key, status);
CREATE INDEX idx_quota_reservations_active_user
    ON quota_reservations (user_id, id)
    WHERE status = 'RESERVED';

-- Backfill reservations for jobs admitted before this migration. OperationPlan already stores the
-- authorization cap used by the old counter-based reservation path.
INSERT INTO quota_reservations
    (user_id, period_key, generation_job_id, estimated_cost, status, finalized_at, created_at, updated_at)
SELECT billed_to_user_id,
       to_char(generation_job_created_at AT TIME ZONE 'UTC', 'YYYY-MM'),
       generation_job_id,
       max_authorized_cost,
       CASE
           WHEN generation_job_status = 'COMPLETED' THEN 'CONSUMED'
           WHEN generation_job_status IN ('FAILED', 'CANCELED') THEN 'RELEASED'
           ELSE 'RESERVED'
       END,
       CASE
           WHEN generation_job_status IN ('COMPLETED', 'FAILED', 'CANCELED')
               THEN CURRENT_TIMESTAMP
           ELSE NULL
       END,
       generation_job_created_at,
       CURRENT_TIMESTAMP
  FROM (
      SELECT DISTINCT ON (gj.id)
             gj.id AS generation_job_id,
             gj.billed_to_user_id,
             gj.status AS generation_job_status,
             gj.created_at AS generation_job_created_at,
             op.max_authorized_cost,
             op.id AS operation_plan_id
        FROM generation_jobs gj
        JOIN operation_plans op ON op.generation_job_id = gj.id
       ORDER BY gj.id, op.id DESC
  ) admitted_jobs
ON CONFLICT (generation_job_id) DO NOTHING;

-- The previous implementation charged authorized cost immediately at reserve time. Move
-- non-consumed reservations back out of credits_used so only CONSUMED work remains charged.
UPDATE usage_windows uw
   SET credits_used = GREATEST(0::numeric, uw.credits_used - refundable.estimated_cost),
       expensive_jobs_active = 0,
       row_version = uw.row_version + 1
  FROM (
      SELECT user_id, period_key, SUM(estimated_cost) AS estimated_cost
        FROM quota_reservations
       WHERE status IN ('RESERVED', 'RELEASED')
       GROUP BY user_id, period_key
  ) refundable
 WHERE uw.user_id = refundable.user_id
   AND uw.period_key = refundable.period_key;

-- Any leftover counter value has no durable reservation identity and cannot safely own capacity.
UPDATE usage_windows
   SET expensive_jobs_active = 0,
       row_version = row_version + 1
 WHERE expensive_jobs_active <> 0;

COMMENT ON COLUMN usage_windows.expensive_jobs_active IS
    'Deprecated projection. Active expensive jobs are derived from quota_reservations status RESERVED.';
