"""Provider-neutral visual directing instructions for the still-image MVP."""

from __future__ import annotations

VISUAL_DIRECTION_INSTRUCTIONS = (
    " For every visual beat, write visual_intent as concise beat-local still-image scene "
    "direction, not as a complete provider prompt and not as generic prose. Refer to established "
    "characters by name and preserve continuity with canonical identity, current appearance, "
    "location canon, and time-of-day while describing only what changes in this beat. Also return "
    "visual_direction as structured shot grammar. visual_direction.shot_size must be one of "
    "ESTABLISHING, WIDE, MEDIUM, MEDIUM_CLOSE_UP, CLOSE_UP, EXTREME_CLOSE_UP. "
    "visual_direction.camera_angle must be one of EYE_LEVEL, LOW, HIGH, OVERHEAD, OVER_SHOULDER, "
    "POV. Keep shot_size independent from camera_angle so combinations such as MEDIUM_CLOSE_UP + "
    "LOW remain possible. lens_mm must be exactly 24, 35, 50, or 85. focus_target names the "
    "single story detail that must remain most readable. action_phase must be BEFORE, IMPACT, "
    "AFTER, or REACTION. subject_placement describes the intended frame placement, foreground is "
    "null or a useful depth layer, and background describes only beat-relevant environment state. "
    "motivated_light must identify a physically motivated source and palette must describe the "
    "local scene palette rather than forcing a global high-contrast look. camera_movement must be "
    "NONE, PUSH_IN, PULL_OUT, PAN, TILT, or PARALLAX. movement_direction is LEFT/RIGHT for PAN, "
    "UP/DOWN for TILT, otherwise null. movement_intensity must be SUBTLE or MODERATE; prefer "
    "SUBTLE for still-image FFmpeg motion. crop_safe_area describes where modest crop room should "
    "remain for the authored movement. Choose camera movement from the actual visual intent, not "
    "from keywords in the title. Static is valid when motion would weaken the shot. Do not "
    "re-specify permanent facial features, body proportions, stable hair identity, skin tone, or "
    "persistent location canon inside visual_intent; those come from canonical records. Only "
    "describe transient pose, expression, current action, temporary injury, wardrobe state, prop "
    "state, environment state, and immediate consequence. Prefer concrete visible details over "
    "adjectives such as cinematic, beautiful, epic, or dramatic. Do not invent text, logos, "
    "subtitles, watermarks, extra people, or unsupported story facts. Each beat must remain "
    "suitable for one coherent static key image with subtle FFmpeg motion applied later."
)
