package com.narrativex.backend.feature.common.api;

public enum ApiErrorCode {
  INVALID_REQUEST,
  VALIDATION_FAILED,
  STORY_CHARACTER_LIMIT_EXCEEDED,
  STORY_TOKEN_LIMIT_EXCEEDED,
  RESOURCE_NOT_FOUND,
  RESOURCE_CONFLICT,
  FEATURE_NOT_AVAILABLE,
  COST_LIMIT,
  FORBIDDEN,
  UNAUTHORIZED,
  INTERNAL_ERROR
}
