CREATE TABLE IF NOT EXISTS plan_entitlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_key VARCHAR(48) NOT NULL,
    version INTEGER NOT NULL,
    watermark_required BOOLEAN NOT NULL,
    max_video_quality VARCHAR(32) NOT NULL,
    max_longform_exports_month INTEGER,
    max_short_exports_month INTEGER,
    max_concurrent_expensive_jobs INTEGER NOT NULL,
    feature_flags_json VARCHAR(2000) NOT NULL,
    monthly_credits DECIMAL(19, 6) NOT NULL,
    active_from TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (plan_key, version)
);

CREATE TABLE IF NOT EXISTS user_plan_assignments (
    user_id VARCHAR(128) PRIMARY KEY,
    plan_key VARCHAR(48) NOT NULL,
    entitlement_version INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    period_start TIMESTAMP WITH TIME ZONE NOT NULL,
    period_end TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_windows (
    user_id VARCHAR(128) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    longform_exports INTEGER NOT NULL DEFAULT 0,
    short_exports INTEGER NOT NULL DEFAULT 0,
    credits_used DECIMAL(19, 9) NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, period_key)
);

CREATE TABLE IF NOT EXISTS quota_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    status VARCHAR(24) NOT NULL,
    estimated_cost DECIMAL(19, 9) NOT NULL
);
